_template/config.yml
utils/schemas/main_config.json

Modified levels in template to match those in document

feat(_template): modified levels to match definitions

---

packs/golden-signals-web/alerts/errors.yml
packs/golden-signals-web/alerts/memory.yml
packs/golden-signals-web/alerts/response_time.yml

fix: typos

---

_template/alerts/baseline-alert.yml
_template/alerts/outlier-alert.yml
_template/alerts/static-alert.yml

Updating some typos; showing support for new faceted baselines; and adding in all options for static conditions to align with "template" approach (the current file is missing options)

fix: updating/repairing alert templates

---

.prettierignore
.prettierrc.js
utils/__tests__/check_pack_uniqueness.test.js
utils/check_pack_uniqueness.js
utils/helpers.js
utils/validate_packs.js

PR to:
* add prettier config & ignore file.
* format files in the utils directory.
Resolves: #87

add prettier config & ignore, format files

---

packs/elasticsearch/dashboards/elasticsearch.json
packs/golden-signals-web/dashboards/golden_signals.json
packs/infrastructure/dashboards/infra_pages_dashboard.json
packs/lamp/dashboards/dashboard.json
packs/mysql/dashboards/mysql.yml
packs/php/dashboards/dashboard.json
packs/prometheus-node-exporter-macos/dashboards/node-exporter-macos.json

Fixes errors in packs (currently don't work in production)

fix(packs): address all validation errors

---

docs/alert-spec.md
docs/config-spec.md
docs/dashboard-spec.md
docs/example-schemas/config.json
docs/rulesets/config.yml
utils/__tests__/validate_packs.test.js
utils/schemas/dashboard_config.json
utils/schemas/logging_config.json
utils/schemas/main_config.json
utils/validate_packs.js

Also fixed dashboard validation issues in all packs

chore(spec): add spec docs for config, alerts, and dashboards

---

.github/workflows/validate_packs.yml
CONTRIBUTING.md
utils/__tests__/check_pack_uniqueness.test.js
utils/__tests__/helpers.test.js
utils/__tests__/validate_images.test.js
utils/check_pack_uniqueness.js
utils/helpers.js
utils/package.json
utils/validate_images.js
utils/yarn.lock

feat(workflow): image validation and tests

---

utils/check_support_level.js

More clean up due to directory changes

Fix path in support label script

---

CONTRIBUTING.md
docs/alert-spec.md
docs/config-spec.md
docs/dashboard-spec.md

This PR updates the configs for alerts, dashboard, and packs to highlight new functionality added to nerdgraph. It also updates the contributing guide.

Config spec update

---

install/infrastructure/infra-agent-standard/install.yml
install/infrastructure/infra-agent-targeted/install.yml

Adds `name` field to the infra-agent install plans

chore(install): add name field

---

packs/nginx/config.yml

fix(nginx): removed mentions of cassandra

---

packs/dotnet/dotnet/config.yml

Search Nurture recommended description and card summary for dotnet quickstart

chore: create dotnet quickstart

---

packs/trendmicro-cloudone-conformity/config.yml

add description for documentation, add keywords, shorten title

Trend Micro Cloud One - Conformity: chore

---

packs/opencensus/config.yml
packs/opentelemetry/config.yml
packs/prometheus/config.yml

Improve the descriptions for a couple of quickstarts

chore: improve description for opencensus, opentelemetry and prometheus

---

utils/schema-doc-generator/README.md

Link was previously borked and not working 🙈

chore: fix broken link in readme

---

packs/apache/config.yml
packs/cassandra/config.yml
packs/consul/config.yml
packs/couchbase/config.yml
packs/elasticsearch/config.yml
packs/haproxy/config.yml
packs/kafka/config.yml
packs/mariadb/config.yml
packs/memcached/config.yml
packs/mongodb/config.yml
packs/mssql/config.yml
packs/mysql/config.yml
packs/nagios/config.yml
packs/nginx/config.yml
packs/postgresql/config.yml
packs/rabbitmq/config.yml
packs/redis/config.yml
packs/varnish/config.yml

Removed the infra requirement on targeted install OHI's + added the requirement on doc installs.

Cleaned up infra requirement

---

packs/apache/dashboards/apache.json
packs/cassandra/dashboards/cassandra.json
packs/consul/dashboards/consul.json
packs/couchbase/dashboards/couchbase.json
packs/haproxy/dashboards/haproxy.json
packs/jmx/dashboards/jmx.json
packs/kafka/dashboards/kafka.json
packs/memcached/dashboards/memcached.json
packs/mongodb/dashboards/mongodb.json
packs/mysql/dashboards/mysql.json
packs/nagios/dashboards/nagios.json
packs/nginx/dashboards/nginx.json
packs/postgresql/dashboards/postgresql.json
packs/rabbitmq/dashboards/rabbitmq.json
packs/redis/dashboards/redis.json
packs/varnish/dashboards/varnish.json

Removed old `::: beyond` text from dashboards

fix: removed beyond text from OHI dashboards

---

install/on-host-integration/apache/install.yml
install/on-host-integration/cassandra/install.yml
install/on-host-integration/couchbase/install.yml
install/on-host-integration/elasticsearch/install.yml
install/on-host-integration/haproxy/install.yml
install/on-host-integration/hashicorp-consul/install.yml
install/on-host-integration/memcached/install.yml
install/on-host-integration/mongodb/install.yml
install/on-host-integration/mssql/install.yml
install/on-host-integration/mysql/install.yml
install/on-host-integration/nagios/install.yml
install/on-host-integration/nginx/install.yml
install/on-host-integration/postgres/install.yml
install/on-host-integration/rabbitmq/install.yml
install/on-host-integration/redis/install.yml
install/on-host-integration/varnish/install.yml

We removed the infra step so users won't know we need to install New Relic Infra. This adds a notice in the UI that we will add it. 
Before we merge this I do have a couple of questions.

Added notice on OHI's that we will install New Relic Infra

---

.github/workflows/pr-open.yml
.github/workflows/stale-message.yml

Closes https://github.com/newrelic/newrelic-observability-packs/issues/218

Add messaging/labeling around new and stale PRs/issues

---

packs/roku/config.yml

- The URL was wrong, I put the correct one linked from https://opensource.newrelic.com
- The description and summary were also problematic, "Build applications that deliver high-quality video to the Roku platform" is misleading, looks like it is a framework to build Roku apps but it is not, it's a New Relic agent to monitor Roku apps.

Fix some errors and improve Roku config file.

---

packs/dotnet/dotnet/config.yml

fixed H1 header

---

packs/kafka/config.yml

Search Nurture's kafka summary recommendation

chore: update Kafka summary

---

packs/java/java/config.yml

Search Nurture's java summary recommendation

chore: update Java summary

---

packs/mongodb/config.yml

Search Nurture summary recommendation

chore: update Mongodb summary

---

packs/php/php/config.yml

Search Nurture recommendations for php summary

chore: update php summary

---

packs/infrastructure/config.yml

Search Nurture summary recommendation

chore: update summary for Infrastructure

---

packs/redis/config.yml

Search Nurture's redis summary recommendation

chore: update Redis summary

---

packs/apache/config.yml

Search Nurture's apache summary recommendations

chore: update apache summary

---

packs/kafka/config.yml

Reduce the Kafka description to 2000 chars

chore: reduce Kafka description to 2000 chars

---

.github/workflows/validate_packs.yml
utils/__tests__/check_quickstart_uniqueness.test.js
utils/__tests__/validate_icon_and_logo.test.js
utils/__tests__/validate_images.test.js
utils/__tests__/validate_quickstarts.test.js
utils/check_quickstart_uniqueness.js
utils/generate-uuids.js
utils/helpers.js
utils/package.json
utils/validate_icons_and_logos.js
utils/validate_images.js
utils/validate_quickstarts.js

Script renaming for quickstarts

feat(rename): update scripts

---

README.md
_template/config.yml
utils/schemas/main_config.json
utils/validate_images.js

feat(rename): catch all updates

---

.github/actions/import-data/README.md
.github/actions/import-data/action.yml
.github/actions/import-data/src/importer.ts
.github/actions/import-data/src/main.ts
README.md
docker-compose.yml
utils/importer/importer.Dockerfile

chore(rename): updating importer from packs to quickstarts

---

.github/workflows/release.yml

Fix pathing in the release workflow

fix: update directory for release workflow

---

.github/workflows/release.yml

Setting fetch depth and locking the semantic-release version

fix: set fetch depth and lock semantic release ver

---

quickstarts/nginx/config.yml

Search Nurture's recommendation for Nginx quickstart description and summary.

chore: create Nginx quickstart

---

quickstarts/infrastructure/config.yml
quickstarts/java/java/config.yml
quickstarts/prometheus/config.yml

The other PRs had nasty merge conflicts, so creating a new one. The content was already approved

Combining SearchNurture PRs for Prometheus, Infrastructure, Java

---

quickstarts/ruby/activerecord/config.yml
quickstarts/ruby/ruby/config.yml

fix 2 remaining wrong references

chore: fix wrong reference to node.js agent

---

quickstarts/macos/config.yml

fix: incorrect description for mac Os

---

quickstarts/cassandra/config.yml

Search Nurture's recommended description and summary for Cassandra

chore: update description for Cassandra quickstart

---

quickstarts/rabbitmq/config.yml

Search Nurture's recommendations for RabbitMQ description and summary

chore: update RabbitMQ quickstart description

---

quickstarts/varnish/config.yml

Search Nurture's recommendations for Varnish description and summary

chore: update Varnish description

---

quickstarts/python/python/config.yml

Search Nurture's recommendations for quickstart description and summary

chore: create Python quickstart description

---

quickstarts/apache/config.yml
quickstarts/cribl_logstream/config.yml
quickstarts/fastly/config.yml
quickstarts/network-data-ingest-and-cardinality/config.yml
quickstarts/network-flow-devices/config.yml
quickstarts/network-routers-and-switches/config.yml
quickstarts/trendmicro-cloudone-conformity/config.yml

Adding the `featured` keyword to the launch partner related quickstarts

feat: Add featured keyword to partner quickstarts

---

install/apm/python/install.yml

chore: fix agent reference

---

quickstarts/pagerduty/pagerduty/config.yml
quickstarts/slack/config.yml
quickstarts/victorops/config.yml
quickstarts/xmatters/config.yml

Improve descriptions for alerting related quickstarts

chore: Improve description for alerting quickstarts

---

.github/pull_request_template.md
CONTRIBUTING.md

This PR explains how the verified icon is applied.

chore: adds info on verified icon

---

quickstarts/lamp/config.yml

small improvement to lamp quickstart

chore: improve lamp description, add summary

---

CONTRIBUTING.md

fixes the explaination for how the verified icon is applied.

chore: corrected support level

---

CONTRIBUTING.md

This PR updates the description template in the contributors guide. This updates it to be more inline with the current descriptions.

fix: update description template

---

README.md

chore: beta readme update

---

install/network/snmp/install.yml
quickstarts/network-data-ingest-and-cardinality/config.yml
quickstarts/network-flow-devices/config.yml
quickstarts/network-routers-and-switches/config.yml

Added snmp installation plan, and added infrastructure keyword so they show up under the infrastructure category.

Network fixes

---

quickstarts/account-data-ingestion/config.yml
quickstarts/account-data-ingestion/dashboards/data_ingestion_breakdown.json
quickstarts/dataingestion/dashboards/data_ingestion_breakdown.json

feat: dashboard showing data ingestion breakdown

---

quickstarts/lacework/config.yml

Added - featured to the keywords
Added the - featured tag for this quickstart

Small update ahead of open GA

---

quickstarts/dotnet/dotnet/config.yml

Search Nurture recommendations for internal linking to docs page

chore: update quickstart

---

quickstarts/nginx/config.yml

Search Nurture recommendations for internal linking to docs page

chore: update quickstart for internal linking

---

quickstarts/trendmicro-cloudone-conformity/config.yml

Add a link to the video overview for the Trend Micro quickstart

chore: Add video link to TrendMicro quickstart

---

quickstarts/infrastructure/config.yml

In order for this tile to show up under Logging, we are adding these log-related keywords.

Add logging keywords

---

quickstarts/mongodb/config.yml

Search Nurture recommendation for Mongodb quickstart.

chore: refresh Mongodb quickstart

---

quickstarts/opentelemetry/config.yml

Improved the description and keywords for the Otel quickstart

feat(opentelemetry): improved description and added some more keywords

---

CONTRIBUTING.md

This PR provides instructions how to set an author.

chore: added author instructions

---

quickstarts/delphix/config.yml

Added a missing reference to the Delphix logo in the quickstart config yaml

chore(delphix): Added logo reference to config yaml

---

install/aws/aws-log-ingestion-s3/install.yml
install/third-party/sendgrid/install.yml
quickstarts/sendgrid/config.yml

feat(sendgrid): Add installPlans for SendGrid Event Webhook and S3 log ingestion

---

quickstarts/kubernetes/kubernetes/config.yml

SN recommended description for Kubernetes

chore: update Kubernetes quickstart description

---

quickstarts/java/websphere-liberty-profile/config.yml

SN recommendations for websphere liberty profile description and  summary

chore: update websphere liberty profile quickstart

---

quickstarts/golang/httprouter/config.yml

SN recommendations for Httprouter quickstart description

chore: update httprouter quickstart description

---

quickstarts/network-routers-and-switches/dashboards/network-routers-and-switches.json

updating existing quickstart dashboard definition to cleanup some NRQL and rename some widgets based on customer feedback

chore: formatting updates for dashboard

---

quickstarts/mlops/superwise/dashboards/superwise.json

Fix Account ID Issue

---

.github/workflows/pr-open.yml

Adds a label based on the files changed.
If a `config.yml` is added it labels the PR `new-quickstart`
If anything inside the `quickstarts` directory is modified, it is labelled `improved-quickstart`

feat: label pr's based on what files have changed

---

README.md
quickstarts/couchbase/config.yml

- Updates the couchbase summary and description
- A quick readme and  contributor update.

chore: updated couchbase config

---

quickstarts/dotnet/episerver-cms/config.yml

Search Nurture recommendations for description and summary.

chore: update episerver cms

---

quickstarts/java/netty/config.yml

Search Nurture recommendation for description and summary.

chore: update description and summary for netty

---

quickstarts/audit/network-data-ingest-and-cardinality-analysis/dashboards/network-data-ingest-and-cardinality.json

Small update to existing quickstart; adding widgets to support new Syslog functionality in NPM ++ SNMP Trap data analysis

chore: update DB to add new syslog functionality and SNMP Traps

---

quickstarts/python/feedparser/config.yml

Search Nurture feedparser recommendations

chore: update quickstart summary and description

---

install/mlops/comet/install.yml

Added a first-party nerdlet as the default install for the comet quickstart.
It is the same nerdlet currently running in tucson i.e [](https://staging.onenr.io/0gbRK7X8lRE
)

feat: Add nerdlet to the comet quickstart

---

install/guided-install.yml
install/java-agent.yml
install/php-agent.yml
install/public-api-performance.yml

Changing the installPlan for the Log Analysis Dashboard, adding the guided-install to it.

fix: changed the installplans for log analysis

---

quickstarts/mlops/comet/config.yml

change support level of mlops/comet

---

quickstarts/mlops/superwise/config.yml

Modify summary content

---

quickstarts/python/webpy/config.yml

Search Nurture recommendations for WebPy description

chore: update WebPy Quickstarts

---

quickstarts/ruby/curb/config.yml

Search Nurture recommendations for Curb quickstart

chore: update Curb quickstart

---

quickstarts/wordpress/config.yml

Search Nurture recommendations for WordPress description and summary

chore: update WordPress quickstart

---

quickstarts/port-monitoring/config.yml

Search Nurture recommendations for summary and description.

chore: update Port quickstart

---

quickstarts/network-routers-and-switches/dashboards/network-routers-and-switches.json

updating NRQL on pre-existing dashboard

chore: small edits to nrql queries to align with latest data model

---

quickstarts/speedscale/config.yml

speedscale - add nr explorer hub

---

quickstarts/php/kohana/config.yml

Search Nurture recommendations for Kohana quickstart

chore: Update kohana quickstart

---

quickstarts/gigamon/config.yml

Gigamon URL link was broken and needed correction.

Updated Gigamon url

---

quickstarts/dotnet/nservicebus/config.yml

Search Nurture recommendations for NServicebus quickstart

chore: update Nservicebus quickstart

---

quickstarts/video/video-web/video-web-akamai/config.yml

Search Nurture recommendations

chore: update video akamai

---

quickstarts/aws/aws-qldb/config.yml

Search Nurture recommended updates to quickstart description

chore: update aws qldb quickstart

---

quickstarts/apis/event/config.yml
quickstarts/apis/logs/config.yml
quickstarts/apis/metric/config.yml
quickstarts/apis/trace/config.yml
quickstarts/blameless/config.yml
quickstarts/drupal/config.yml
quickstarts/golden-signals-web/config.yml
quickstarts/lamp/config.yml
quickstarts/lighthouse/config.yml
quickstarts/oracle/inet-oracle-driver/config.yml
quickstarts/pagerduty/pagerduty/config.yml
quickstarts/pivotal-tracker/config.yml
quickstarts/quantum-metric/config.yml
quickstarts/redhat/red-hat-enterprise-linux/config.yml
quickstarts/signl4/config.yml
quickstarts/victorops/config.yml
quickstarts/wordpress/config.yml
quickstarts/xmatters/config.yml

This PR updates quickstarts that had no defined keywords.

Keyword updates

---

.github/workflows/pr-merged.yml
quickstarts/golden-signals-web/config.yml

Using this branch to test if the Github workflow will update a quickstart just w/ a PR.

TEST - Update Quickstart via workflow

---

.github/workflows/pr-merged.yml

Need to update the branch from which the workflow pulls its code...

TEST: update branch referrenced in workflow

---

install/third-party/biztalk360/install.yml
quickstarts/biztalk360/config.yml

chore: added installplans for biztalk360

---

quickstarts/mlops/sagemaker/config.yml

We had a 404 with the docs. PR is the fix

fix: Fix the correcrt link to the docs

---

install/third-party/biztalk360/install.yml
quickstarts/biztalk360/dashboards/biztalk360.json

fix: Removed account id from dashboard and typo in description

---

quickstarts/circleci/config.yml

per request, description updated for circleci dashboard.

chore: updated description for circleci dashboard

---

quickstarts/golden-signals-web/config.yml

this time the feature flag is on :D

more tests

---

.github/workflows/validate_packs.yml

update pr number interpolation in ensure schema compliance check

fix: update pr number interpolation in check

---

CONTRIBUTING.md

adds context around the use of the permission field in dashboard JSON

chore: added permissions info

---

.github/workflows/release.yml

Docs generation step was missing some env variables

add needed env variables to workflow step

---

quickstarts/jira-errors/config.yml

Added keyword "newrelic partner"

Adding keyword for partner

---

quickstarts/java/mule-esb/config.yml
quickstarts/java/mule-esb/dashboards/java.json

This PR removes a linkedEntityGuid that was causing an error on this PR #799 it also adds the partner keyword as well as prettifies the JSON.  😉

chore: fixes dashboard

---

install/solutions-hub/dashboards/install.yml
quickstarts/oma-data-gov/config.yml

At the recommendation from some people like Stijn and others in `help-newreic-io` I've created a `dummy` install plan in order to allow users to have relatively effortless dashboard install.
- [✅ ] Did you check you NRQL syntax? - Does it work?
- [ ✅] Did you check your dashboard image quality? -  Do they look good?
- [✅ ] Did you check that your alerts actually work?
- [ ✅] Did you include an InstallPlan and Documentation reference?
- [✅ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ✅] Did you attach images of your dashboards to the PR so we can see them working?

fix: Add dummy install plan to oma-data-gov

---

CONTRIBUTING.md

fixes some broken docs references since changed to auto generated schema docs, + some other improvements

chore: updating the contributor guide

---

quickstarts/react-native/config.yml

SN react native recommendations

Update React Native quickstart

---

quickstarts/aws/aws-health/config.yml

SN recommendations for aws health description and summary

Chore: Update AWS Health Quickstart

---

.github/workflows/pr-merged.yml
.github/workflows/validate_install_plans.yml
.github/workflows/validate_packs.yml
utils/create-validate-install-plans.js
utils/create_validate_pr_quickstarts.js
utils/package.json
utils/yarn.lock

* Add the node agent to validate/publish scripts
* Add custom event for install plans and quickstarts to allow for
tracking in New relic one

add NR events to validate/publish workflows

---

install/aws/aws-cloudwatch-metric-streams/install.yml
install/aws/aws-infrastructure-monitoring/install.yml
install/azure/azure-infrastructure-monitoring/install.yml
install/gcp/gcp-infrastructure-monitoring/install.yml

fix(installPlans): Remove nerdlets from cloud install plans

---

quickstarts/circleci/config.yml
quickstarts/cribl-logstream/config.yml
quickstarts/delphix/config.yml
quickstarts/kentik/config.yml
quickstarts/network-flow-devices/config.yml
quickstarts/network-routers-and-switches/config.yml
quickstarts/network-syslog/config.yml
quickstarts/releaseiq/config.yml
quickstarts/speedscale/config.yml
quickstarts/trendmicro-cloudone-conformity/config.yml

Updated the featured partner quickstarts
Added keyword in config file:
- Speedscale
- Delphix
- CircleCI
- ReleaseIQ
Removed keyword in config file:
- Cribl
- Kentik (x4)
- Trend Micro
**N/A below:**

Update featured quickstarts

---

quickstarts/consul/config.yml
quickstarts/memcached/config.yml
quickstarts/postgresql/config.yml

Adding in missing summaries that we were made aware of via the link below.
Relates to: #904

chore: add missing summaries for consul, memcached, postgresql

---

quickstarts/java/jetty/config.yml
quickstarts/java/tomcat/config.yml
quickstarts/java/wildfly/config.yml

We've recently added guided/targeted installation support for jetty and wildfly application servers.  This PR contains updates to the corresponding quickstarts for jetty and wildfly.  

chore: update jetty and wildfly quickstarts to use targeted install

---

quickstarts/apache/dashboards/apache.json
quickstarts/cassandra/dashboards/cassandra.json
quickstarts/consul/dashboards/consul.json
quickstarts/couchbase/dashboards/couchbase.json
quickstarts/elasticsearch/dashboards/elasticsearch.json
quickstarts/haproxy/dashboards/haproxy.json
quickstarts/kafka/dashboards/kafka.json
quickstarts/kubernetes/kubernetes/dashboards/kubernetes.json
quickstarts/memcached/dashboards/memcached.json
quickstarts/mongodb/dashboards/mongodb.json
quickstarts/mysql/dashboards/mysql.json
quickstarts/nginx/dashboards/nginx.json
quickstarts/postgresql/dashboards/postgresql.json
quickstarts/rabbitmq/dashboards/rabbitmq.json
quickstarts/redis/dashboards/redis.json
quickstarts/varnish/dashboards/varnish.json

This PR changes the queries on on-host integration dashboards to dimensional metrics. This is part of a company initiative to adopt dimensional metrics storage as standard.

Dimensional Metrics dashboards migration

---

quickstarts/infrastructure/dashboards/infra_pages_dashboard.json

On the page "Infrastructure Metrics",  "System Metrics" widget was detected wrong  closing curly brackets  at the query body

Fix broken JSON formatting

---

install/third-party/cloudflare/install.yml
quickstarts/cloudflare/config.yml

Changing the data ingest doc link to the NR doc.

chore: updated doc link to our doc

---

quickstarts/oma-data-gov/dashboards/data-ingest-entity-breakdown.json

- [ X] Did you check you NRQL syntax? - Does it work?
- [ X] Did you check your dashboard image quality? -  Do they look good?
- [ X] Did you check that your alerts actually work?
- [ X] Did you include an InstallPlan and Documentation reference?
- [ X] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ X] Did you attach images of your dashboards to the PR so we can see them working?

feat: Added "about this dashboard" page to the entity breakdown dashboard

---

quickstarts/prometheus-remote-write/dashboards/prometheus-remote-write-monitoring.json

Links to the high cardinality doc from the prometheus consumer dashboard created for customers.

Add high cardinality information

---

.config/yamllint/config.yml
.github/workflows/yaml-lint.yml

* added new workflow which runs yamllint on push
* added yamllint config file

add yaml validation

---

quickstarts/kubernetes/coredns/dashboards/coredns-dashboard/coredns-dashboard.json

This PR is updating a visualization to a stacked bar instead of a pie chart.

updated visualization to stacked bar

---

CONTRIBUTING.md

Minor change to update table of contents

Fix contributor doc

---

.github/workflows/pr-merged.yml
.github/workflows/quickstarts.eu-production.yml
.github/workflows/quickstarts.production.yml
.github/workflows/quickstarts.staging.yml
.github/workflows/reusable.quickstart_submission.yml

Adds license key to reusable workflows so that we get update events for tracking.

Add license key to resuable submit workflow

---

quickstarts/basic-dashboard/config.yml

As I discussed with @AlecIsaacson, I added installPlans like the full stack observability dashboard: https://github.com/newrelic/newrelic-quickstarts/blob/main/quickstarts/full-stack-observability/config.yml

add installPlans

---

install/basic-dashboard/install.yml
quickstarts/basic-dashboard/config.yml

As I discussed with @aswanson-nr, I added a file, install.yml and (updated installPlans)

remove installPlans and add install.yml

---

quickstarts/ibmmq/config.yml

This a small enhancement on the description provided on the new IBM MQ quickstart.

update IBM MQ quickstart description

---

quickstarts/atlassian/atlassian-jira/config.yml

Attaches the JIRA install plan to the JIRA quickstart.

Attach the install plan for the JIRA quickstart

---

data-sources/netlify-builds/config.yml
data-sources/netlify-logs/config.yml

Add `browser agent` keyword to the netlify quickstarts

feat: Add browser agent keyword to netlify

---

quickstarts/circleci/config.yml

Includes new headings and a new link to a discussion board. We'll be calling this out during the FutureStack22 keynote so want to ensure that it's available for users.

Updating description

---

install/third-party/codestream/github-cs/install.yml
quickstarts/codestream/github-cs/config.yml

NR-20913: integration of github for codestream

---

install/third-party/full-story/install.yml
quickstarts/full-story/config.yml

NR-20913: integration of full-story

---

install/third-party/fluentd-plugin-for-logs/install.yml
quickstarts/fluentd-plugin-for-logs/config.yml

NR-20913: integration of fluentd-plugin-for-logs

---

install/third-party/fluent-bit-plugin-for-logs/install.yml
quickstarts/fluent-bit-plugin-for-logs/config.yml

NR-20913: integration of fluent-bit-plugin-for-logs

---

install/third-party/f5/install.yml
quickstarts/f5/config.yml

NR-20913: integration of F5

---

install/third-party/oma-qf/install.yml
quickstarts/oma-qf/config.yml

Here for “Customer Experience Quality Foundation quickstart” shows See Installation docs , so for that I have added install plans (third-party-oma-qf) then it can redirect to signup-page before seeing the installation docs. Added “oma-qf” folder in third-party and also added install plans in oma-qf config.yml file.

 Added install plans for  Customer Experience Quality Foundation

---

install/third-party/quantum-metric/install.yml
quickstarts/quantum-metric/config.yml

Here for “Quantum Metric quickstart” shows See Installation docs , so for that I have added install plans (third-party-quantum-metric) then it can redirect to signup-page before seeing the installation docs. Added “quantum-metric” folder in third-party and also added install plans in quantum-metric config.yml file.

refactor(Quantum-metric): Added install plans for quantum metric

---

.github/workflows/pr-open.yml

* Moves all input values to environment variables to prevent command
injection

Move input out of script declaration

---

quickstarts/dotnet/asp-dotnet-mvc/config.yml

This quickstart has some missing dashboard screenshots, this will trigger new mutations that will get it updated with the correct URLs.

Trigger deployment of ASP .NET MVC

---

alert-policies/mongodb/EmptyDatabase.yml
alert-policies/mongodb/FailedCommandCount.yml

Added new alerts for the MongoDB quickstart.

feat(pack): Added alerts for mongodb quickstart

---

quickstarts/java/tomcat/config.yml

Ticket ID: https://issues.newrelic.com/browse/NR-34609
Description: Adding tomcat to most popular list

NR-34609: Add tomcat to most popular list

---

utils/preview.ts

* Update logic to only add the port if the environment variable has been
provided

Preview port param fix

---

.github/workflows/validate_packs.yml
dashboards/azure-api-management/azure-api-management.json
dashboards/battlesnake-server-status/battlesnake-server-status.json
dashboards/om-bofu-analysis/om-bofu-analysis.json
dashboards/synthetics-private-minions/synthetics-private-minions.json
utils/dashboard-helper.ts
utils/package.json

* added script to check all dashboards for unwanted content and configuration
TODO - write dashboard helper so it doesn't check every dashboard on each PR

Dashboard helper script

---

quickstarts/vercel/config.yml

chore: update vercel

---

quickstarts/wayscript/config.yml

Updated docs to the right links and added additional resources.

Update doc links

---

alert-policies/dotnet/HighMemoryUsage.yml
alert-policies/dotnet/LowApdexScore.yml
quickstarts/dotnet/csharp/config.yml

Ticket : https://issues.newrelic.com/browse/NR-52346 
Description: Worked on content part and typo

NR-52346: worked on observations

---

install/third-party/jenkins/install.yml
quickstarts/jenkins/config.yml

Added install plan for Jenkins.

feat: add installPlan for Jenkins

---

quickstarts/opentelemetry/config.yml

By adding languages it supports. Also change the Docs link to a more topical landing page.

Improve search results for OTel

---

alert-policies/calico/higher-number-of-dataplane-failures.yml
alert-policies/calico/higher-number-of-failed-ipsets.yml
alert-policies/calico/higher-number-of-iptable-save-failures.yml

Adding alerts for Calico

---

_template/alert-policies/example-alert-policy/baseline-alert.yml
_template/alert-policies/example-alert-policy/static-alert.yml

This PR removes currently unsupported `operator` terms. This commit can be reverted once we allow support to other `operator` terms

Update alert policy template

---

quickstarts/roku/config.yml

Add featured quickstart Roku

---

.github/CODEOWNERS

Add @seemantk to the codeowners file. This will cause Github to request a review from them whenever a PR is created with changes to the `/dashboards/` directory.

Update CODEOWNERS to include PM approval

---

CONTRIBUTING.md
_template/dashboards/example-dashboard/example-dashboard.json
utils/lib/Dashboard.ts
utils/sanitize_dashboards.ts

Adds the `variables` key to the `Dashboard` type similar to `pages` but makes it optional

Dashboard variables type addition

---

dashboards/traefik/traefik.json
quickstarts/traefik/config.yml

- Added dashboard variables for Traefik
- Added Prometheus Agent install plan

Added dashboard variables for Traefik.

---

quickstarts/etcd/config.yml

Just updating the `etcd` quickstart title.

update etcd quickstart title

---

dashboards/gcp-cloud-spanner/gcp-cloud-spanner.json

added a few new tables to dashboard for GCP spanner.

chore: add table to dashboard

---

quickstarts/apache-flink/config.yml

Search Nurture recommended content updates to quickstart.

Chore: update Apache Flink quickstart

---

quickstarts/python/psycopg2/config.yml

Search Nurture recommended content updates

Chore: update psycopg2 quickstart

---

quickstarts/argocd/config.yml
quickstarts/cribl-logstream/config.yml
quickstarts/gigamon/config.yml
quickstarts/lacework/config.yml
quickstarts/vercel/config.yml
quickstarts/zebrium/config.yml

Changes the display names to match to their data source counter parts. 
Changes made: 
- Vercel Logs -> Vercel
- ArgoCD Quickstart -> ArgoCD
- Cribl Logstream -> Cribl
- Lacework Integration -> Lacework
- Gigamon New Relic -> Gigamon
- Zebrium Root Cause as a Service -> Zebrium

Update quickstart titles 

---

quickstarts/aws/amazon-cloudfront-logs/config.yml
quickstarts/cloudflare/config.yml

fixed references to alerts for cloudflare and cloudfront.

chore: reference alerts

---

utils/constants.ts
utils/lib/Alert.ts
utils/lib/__tests__/Alert.test.js
utils/set-alert-policy-required-datasources.ts

We found a few issues in our approach to setting required data sources on alert policies and dashboards, this fixes those problems.

Proper queries and updated error handling for required data sources

---

utils/set-alert-policy-required-datasources.ts

If a Quickstart has no data sources, it is skipped.

No data source quickstarts are skipped

---

data-sources/lacework/config.yml

Add "security" categoryTerm to Lacework datasource

---

data-sources/aws-cloudfront/config.yml

fixing casing issue for Amazon Cloudfront only.

chore: fix casing issue

---

data-sources/zebrium/config.yml
quickstarts/zebrium/config.yml

Removing Zebrium from the mlops category per request

Clean up mlops category

---

data-sources/contentsquare/config.yml
data-sources/perfmon/config.yml
data-sources/unix/config.yml
data-sources/wayscript/config.yml

I incorrectly hid a few data sources in a previous PR, this re-adds the ones that shouldn't have been removed.

fix: Show some mistakenly hidden data sources

---

dashboards/mobile-crash-analytics/crash-analytics.json

This dashboard gives the visibility about the mobile application crashes, their frequency, affect versions etc.
There is no dashboard available for crash analysis and there is lot of manual effort each time when this type of dashboard is needed.
Small fix **updating the name of the dashboard**

Updating the name of the dashboard

---

dashboards/mongodb-prometheus/mongodb.json
quickstarts/mongodb-prometheus/config.yml

This PR fixes documentation links on the mongodb prometheus quickstart.

Fix mongodb documentation links

---

quickstarts/nuxtjs/config.yml

SN content optimization for nuxt.js

chore: update nuxt.js content

---

quickstarts/redpanda/config.yml

SN recommended content optimizations

chore: update redpanda content

---

quickstarts/dojo/config.yml

SN recommended changes to dojo quickstart content

chore: update dojo content

---

quickstarts/dotnet/blazor-server/config.yml

SN recommended blazor server content optimizations

chore: update blazor server content

---

quickstarts/redmine/config.yml

SN recommended content optimizations to Redmine

chore: update redmine content

---

utils/constants.ts
utils/create-validate-data-sources.ts
utils/create-validate-install-plans.ts
utils/lib/Dashboard.ts
utils/lib/nr-graphql-helpers.ts

* fixes some code that was dropping errors

Stop hiding errors

---

quickstarts/openai/config.yaml

Small change to trigger the associated workflows again.
Merge after #1672

Associate OpenAI dashboard with data source

---

dashboards/jfrog-artifactory/jfrog-artifactory.json
dashboards/jfrog-xray/jfrog-xray.json
quickstarts/jfrog-platform/config.yml

Update JFrog quickstart name, description, and dashboard descriptions
--

Feat update jfrog quickstart

---

data-sources/argocd/config.yml

Remove commas in argocd

---

quickstarts/core-web-vitals/config.yml

Fixed type

---

.github/workflows/pr-merged.yml

fix: use needs instead of steps

---

quickstarts/gcp/gcp-alloydb/config.yml

Updates the dataSource field to dataSourceIds

feat: Update config to use dataSourceIds field

---

quickstarts/redmine/config.yml

"Why monitor your Redmine app?" got repeated. 

Updating config.yml

---

data-sources/mern/config.yml
quickstarts/mern/config.yml

Ticket: [NR-103241](https://issues.newrelic.com/browse/NR-103241)
Description: updated IO page content of MERN
Preview image :

NR 103241 : MERN - updated IO page content

---

dashboards/lighttpd/lighttpd.json

Ticket : [NR-102744](https://issues.newrelic.com/browse/NR-102744), [NR-102741](https://issues.newrelic.com/browse/NR-102744)
Description: updated urls in About section of  lighttpd dashboard and logo url change.

NR 102744: Lighttpd - updated urls in About section & logo url for dashboard

---

quickstarts/oma-data-gov/config.yml

Currently this quickstart is missing its data source, this PR adds a small change to force an update through the pipeline

Small edit to force update

---

quickstarts/elixir/config.yml

The Elixir quickstart is missing some data in certain environments, this PR will trigger everything and get things back in sync.

Small PR to trigger a release of Elixir quickstart

---

quickstarts/apm-change-tracking/config.yml
quickstarts/audit/account-data-ingestion-analysis/config.yml
quickstarts/audit/infrastructure-integrations-data-analysis/config.yml
quickstarts/audit/k8s-log-ingestion-analysis/config.yaml
quickstarts/audit/log-ingestion-analysis/config.yml
quickstarts/aws/amazon-security-lake/config.yml
quickstarts/battlesnake/config.yml
quickstarts/gitlab/config.yml
quickstarts/hivemq/config.yml
quickstarts/ibmmq/config.yml
quickstarts/kubernetes/azure-kubernetes-service/config.yml
quickstarts/kubernetes/google-kubernetes-engine/config.yml
quickstarts/mobile-crash-analytics/config.yml
quickstarts/mobile-network-performance/config.yml
quickstarts/mobile/config.yml
quickstarts/sendgrid/config.yml
quickstarts/squid-prometheus/config.yml
quickstarts/sybase/config.yml
quickstarts/synthetics/private-locations/config.yml
quickstarts/tvos/config.yml
quickstarts/video/video-android/config.yml

Resubmitting quickstarts with extra white space or added dataSourceIds to associate quickstarts with proper data sources.

feat: Update quickstarts to have data sources

---

quickstarts/azure/azure-app-service-plan/config.yml
quickstarts/azure/azure-disk-storage/config.yml
quickstarts/azure/azure-event-grid-partner-topics/config.yml
quickstarts/azure/azure-event-grid-subscriptions/config.yml

Fixing errors in the docs URLs for recent Project NorthStar Azure Cohort 1 quickstarts.

Project NorthStar Azure - Cohort 1 Quickstart docs fixes

---

quickstarts/magento-business-insights/config.yml

Update config.yml of magento business insights

---

alert-policies/dotnet-core/TransactionsError.yml

This PR fixes a typo, a duplicate "the".

Fix: typo, duplicate "the" in TransactionsError.yml

---

install/third-party/github/install.yml

ticket: https://issues.newrelic.com/browse/NR-121639 
Comments received for this PR to update the data source description: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/569 
Hence, I have updated the text based on the above received comments.
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our …

fix(dependabot): Update data source description for dependabot

---

data-sources/redpanda/config.yml

I would like to update the description of this data source based on our Redpanda documentation instructions here: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/redpanda-integration/

Redpanda: Update heading description

---

dashboards/mongodb-prometheus/mongodb.json

The current dashboard is not working due an error in one of the variables

Fixed error in variable

---

alert-policies/sendmail/HighMemory.yml

Ticket: https://issues.newrelic.com/browse/NR-146300
Alert: https://onenr.io/08jqabG9djl

NR146300- sendmail alert query update

---

dashboards/sendmail/sendmail.json

Ticket: https://issues.newrelic.com/browse/NR-146298
Dashboard url: https://onenr.io/0bRKpEVAkjE 
Following points have been updated in PR  :
1. Image URL on the dashboard has to be updated
2. Link on "Add data" has to be updated to "https://one.newrelic.com/catalog-pack-details?state=06d45c23-4742-51f3-49fe-d5d51e9f7174"
3. Link on troubleshoot here has to be updated to "https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/flex-integration-tool-build-your-own-integration/"
_The owners of this repo are not experts in the subject …

NR146298 : Sendmail - updated dashboard 'About' section

---

dashboards/mexn/dashboard.json

**Ticket**: https://issues.newrelic.com/browse/NR-115597
**Description** : Updated logo url on mexn dashboard.

Updated logo url on mexn dashboard

---

quickstarts/atlassian/atlassian-jira/config.yml

Ticket: https://issues.newrelic.com/browse/NR-114334

NR-114334 Atlassian-JIRA Fix-Install-Button

---

dashboards/docker-otel/docker-otel.json

Fixes dockerstats dashboard name

fix: Docker-otel dashboard typo

---

data-sources/amazon-eks-on-aws-fargate/config.yml

Updated data source definition for amazon-eks-on-aws-fargate
merketplace PR:https://source.datanerd.us/nr1-dev-experience/marketplace/pull/702
Data source id: amazon-eks-on-aws-fargate
Ticket: https://issues.newrelic.com/browse/NR-151327
To Release this feature , adding nerdlet state to this data source.
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are …

Updated data source definition for amazon-eks-on-aws-fargate

---

quickstarts/snowflake/config.yml

Added a keywords of snowflake quickstart in Add data and Stack page.
- NR1_addData  
- NR1_sys
[NR-151490](https://issues.newrelic.com/browse/NR-151490)

Adding a keyword of snowflake quickstart into a Add Data and Stack page

---

quickstarts/aerospike/config.yml

**Description**: Added a keywords of aerospike quickstart in Add data and Stack page.
- NR1_addData
- NR1_sys
**JIRA ticket**: https://issues.newrelic.com/browse/NR-151502

Adding a keyword of aerospike quickstart into a Add Data and Stack page

---

data-sources/tvos-mobile/config.yml

Added marketplace IF data source id to TvOS.
data source id: `tvos-mobile`
MarketPlace PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/581 
Jira: https://issues.newrelic.com/browse/NR-151468

chore(Datasource): Add marketplace IF data source id to TvOS

---

quickstarts/redmine/config.yml

Updating category for Redmine by adding keyword "apm" and "language agent"

Updated category for redmine quickstart

---

data-sources/amazon-cloudwatch-metric-streams/config.yml

Added marketplace IF data source id to Amazon CloudWatch Metric Streams.
data source id: `amazon-cloudwatch-metric-streams`
MarketPlace PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/711 
Jira: https://issues.newrelic.com/browse/NR-151478
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our …

chore(Datasource): Add marketplace IF data source id to AWS cloud watch

---

data-sources/redis-enterprise/config.yml

Added marketplace IF data source id to Redis Enterprise.
data source id: `redis-enterprise`
MarketPlace PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/681
Jira: https://issues.newrelic.com/browse/NR-151492
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a …

chore(Datasource): Add marketplace IF data source id to Redis Enterprise

---

data-sources/ibmmq-integration-docs/config.yml

Added marketplace IF data source id to IBM MQ.
data source id: `ibmmq-integration-docs`
MarketPlace PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/694
Jira: https://issues.newrelic.com/browse/NR-151499
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content …

chore(Datasource): Add marketplace IF data source id to IBM MQ

---

quickstarts/velero-prometheus/config.yml
quickstarts/video/video-android/config.yml
quickstarts/video/video-chromecast/config.yml
quickstarts/video/video-ios-tvos/config.yml
quickstarts/video/video-web/video-web-akamai/config.yml
quickstarts/video/video-web/video-web-html5/config.yml
quickstarts/video/video-web/video-web-jwplayer/config.yml
quickstarts/video/video-web/video-web-theplatform/config.yml
quickstarts/video/video-web/video-web-videojs/config.yml
quickstarts/vmware/vmware-esxi/config.yml
quickstarts/windows/windows-certs/config.yml
quickstarts/windows/windows-desktop/config.yml
quickstarts/windows/windows-server/config.yml
quickstarts/winservices/config.yml
quickstarts/wordpress-fullstack/config.yml
quickstarts/wordpress/config.yml
quickstarts/xmatters/config.yml
quickstarts/zenduty/config.yml
quickstarts/zipkin/config.yml

**JIRA ticket**: https://issues.newrelic.com/browse/NR-151537
**Description**: Updated  keywords of quickstart in Add data and Stack page.

Updated keywords for quickstarts

---

quickstarts/active-directory/config.yml
quickstarts/ads/web/ads-web-gpt/config.yml
quickstarts/ads/web/ads-web-prebid/config.yml
quickstarts/ajax/config.yml
quickstarts/ansible-automation-controller/config.yml
quickstarts/apache-flink/config.yml
quickstarts/apache-hadoop/config.yml
quickstarts/apache-zooKeeper/config.yml
quickstarts/apis/event/config.yml
quickstarts/apis/logs/config.yml
quickstarts/apis/metric/config.yml
quickstarts/apis/trace/config.yml

**Jira Ticket:** https://issues.newrelic.com/browse/NR-151520
**Description:** Added keywords for the below quickstarts:
1. Active-directory
2. Ads-Web-Gpt
3. Ads-We-Prebid
4. Ajax
5. Ansible-automation-controller
6. Apache-Flink
7. Apache-Hadoop
8. Apache-zooKeeper
9. Apis
10. event
11. logs
12. metrics
13. trace
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. …

Added keywords for the quickstarts.

---

data-sources/metric-api/config.yml

Updated data source definition for metric-api
marketplace PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/708
Data source id: zipkin
Ticket: https://issues.newrelic.com/browse/NR-151327
To Release this feature , adding nerdlet state to this data source.
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, …

Updated data source definition for metric-api

---

quickstarts/active-directory/config.yml
quickstarts/ads/web/ads-web-gpt/config.yml
quickstarts/ads/web/ads-web-prebid/config.yml
quickstarts/ajax/config.yml
quickstarts/ansible-automation-controller/config.yml
quickstarts/apache-flink/config.yml
quickstarts/apache-hadoop/config.yml
quickstarts/apache-zooKeeper/config.yml
quickstarts/apis/event/config.yml
quickstarts/apis/logs/config.yml
quickstarts/apis/metric/config.yml
quickstarts/apis/trace/config.yml

**Jira Ticket:** https://issues.newrelic.com/browse/NR-151578
**Description:** Removed NR1_sys keyword for the below quickstarts:
1. Active-directory
2. Ads-Web-Gpt
3. Ads-Web-Prebid
4. Ajax
5. Ansible-automation-controller
6. Apache-Flink
7. Apache-Hadoop
8. Apache-zooKeeper
9. event
10. logs
11. metrics
12. trace
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. …

Removed NR1_sys keywords.

---

quickstarts/aerospike/config.yml
quickstarts/velero-prometheus/config.yml
quickstarts/video/video-android/config.yml
quickstarts/video/video-chromecast/config.yml
quickstarts/video/video-ios-tvos/config.yml
quickstarts/video/video-web/video-web-akamai/config.yml
quickstarts/video/video-web/video-web-html5/config.yml
quickstarts/video/video-web/video-web-jwplayer/config.yml
quickstarts/video/video-web/video-web-theplatform/config.yml
quickstarts/video/video-web/video-web-videojs/config.yml
quickstarts/vmware/vmware-esxi/config.yml
quickstarts/windows/windows-certs/config.yml
quickstarts/windows/windows-desktop/config.yml
quickstarts/windows/windows-server/config.yml
quickstarts/winservices/config.yml
quickstarts/wordpress-fullstack/config.yml
quickstarts/wordpress/config.yml
quickstarts/xmatters/config.yml
quickstarts/zenduty/config.yml
quickstarts/zipkin/config.yml

JIRA ticket: https://issues.newrelic.com/browse/NR-151592
Description: Cleanup keyword - NR1_sys

removed keyword - NR1_sys

---

quickstarts/snowflake/config.yml

Reverts newrelic/newrelic-quickstarts#1937
Ticket: https://issues.newrelic.com/browse/NR-151490
Summary: Reverting it back, as R&D of our product manager is yet to be completed, they can guide us further

Revert "Adding a keyword of snowflake quickstart into a Add Data and Stack page"

---

quickstarts/gridgain/config.yml

Updates the data source id for GridGain to be correct.

fix: Update to correct data source id

---

data-sources/langchain/config.yml

https://issues.newrelic.com/browse/NR-158730

Updated datasource Id

---

data-sources/mux/config.yml

Adding tag to get mux into add data for upcoming marketing.

fix mux add data

---

alert-policies/azure-machine-learning/ModelDeployFailed.yml
quickstarts/azure/azure-machine-learning/config.yml

[Product Partnerships] Added New Alert For Azure ML

---

data-sources/collectd/config.yml

https://issues.newrelic.com/browse/NR-111177
https://source.datanerd.us/nr1-dev-experience/marketplace/pull/547

NR-111177 - Migrate collectd datasource

---

data-sources/battlesnake/config.yml

https://issues.newrelic.com/browse/NR-114088
https://source.datanerd.us/nr1-dev-experience/marketplace/pull/572

NR-114088 - Migrate battlesnake datasource

---

data-sources/github-for-codestream/config.yml

https://issues.newrelic.com/browse/NR-121162
https://source.datanerd.us/nr1-dev-experience/marketplace/pull/633

NR-121162 - Migrate github-for-codestream datasource

---

data-sources/grafana-prometheus-integration/config.yml

Updated data source definition for grafana-prometheus-integration
marketplace PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/913
Data source id:  grafana-prometheus-integration
Ticket: https://issues.newrelic.com/browse/NR-151753
To Release this feature , adding nerdlet state to this data source.
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter …

feat(grafana): Updated data source definition for grafana-prometheus-integration

---

data-sources/netlify-logs/config.yml

Added marketplace IF data source id to Netlify logs.
data source id: netlify-logs
MarketPlace PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/892
Jira: https://issues.newrelic.com/browse/NR-167424
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content …

chore(Datasource): Add marketplace IF data source id to Netlify logs

---

data-sources/amazon-cloudwatch-metric-streams/config.yml

Add keyword in data source config file for AWS cloud watch to reflect the IF changes in marketplace.

chore(Datasource): Add keyword in data source config for AWS cloud watch

---

dashboards/nvidia-dcgm/nvidia-dcgm.json

Ticket URL: https://new-relic.atlassian.net/browse/NR-179135
Description: Updated the add data URL and logo URL in the nvidia-dcgm dashboard.

NVIDIA-DCGM: Dashboard updates

---

.github/workflows/pr-merged.yml
.github/workflows/release.yml
.github/workflows/submit-gate.yml
utils/package.json
utils/yarn.lock

Pulls in the latest changes from the `release` branch

Pull in latest `release` changes

---

quickstarts/aws/amazon-cloudwatch-network-monitor/config.yml
quickstarts/aws/aws-lex/config.yml

[Product Partnerships] Fixing issues with showing up alerts.

---

quickstarts/aws/amazon-cloudwatch-network-monitor/config.yml
quickstarts/aws/amazon-security-lake/config.yml
quickstarts/aws/amazon-vpc-lattice/config.yml
quickstarts/aws/aws-apprunner/config.yml
quickstarts/aws/aws-lambda-telemetry-extension/config.yml
quickstarts/aws/aws-lex/config.yml
quickstarts/aws/aws-polly/config.yml
quickstarts/aws/aws-rekognition/config.yml
quickstarts/aws/aws-textract/config.yml
quickstarts/aws/aws-translate/config.yml
quickstarts/aws/aws-verified-access/config.yml

Jira ticket: https://new-relic.atlassian.net/browse/NR-227510
Description: Update AWS quickstarts with CloudWatch Metric Stream data source.

[Product Partnerships] Added Fix For AWS Quickstart

---

quickstarts/k6-prometheus/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-232582
**Description:** Spotted description for k6 Prometheus (remote write) extends beyond the confines of the description box.
Attaching the screenshot of documentation description

Updated the description of k6 Prometheus (remote write)

---

data-sources/langchain/config.yml
quickstarts/mlops/langchain/config.yml

This PR keeps the langchain data source pointed to its current config so that the many quickstarts using it continue to have the same install experience. We are instead updating the langchain quickstart to point to the new nr-ai-monitoring data source to have the new install experience. 
**N/A for this change**
~- [ ] Did you check you NRQL syntax? - Does it work?~
~- [ ] Did you include a Data source and Documentation reference?~
~- [ ] Are all documentation links publicly accessible?~
~- [ ] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?~
~- [ ] Did you check your descriptive content for spelling and grammar errors?~
~- [ ] Did you review your content with a subject matter …

fix(Langchain): Update data source and quickstart to use correct IDs

---

quickstarts/aws/amazon-appstream/config.yml
quickstarts/aws/amazon-aurora/config.yml
quickstarts/aws/amazon-backup/config.yml
quickstarts/aws/amazon-cloudsearch/config.yml
quickstarts/aws/amazon-cloudwatch-internet-monitor/config.yml
quickstarts/aws/amazon-cloudwatch-network-monitor/config.yml
quickstarts/aws/amazon-codebuild/config.yml
quickstarts/aws/amazon-database-migration-service/config.yml
quickstarts/aws/amazon-datasync/config.yml
quickstarts/aws/amazon-eks-on-aws-fargate/config.yml
quickstarts/aws/amazon-elastictranscoder/config.yml
quickstarts/aws/amazon-gamelift/config.yml
quickstarts/aws/amazon-inspector/config.yml
quickstarts/aws/amazon-keyspaces/config.yml
quickstarts/aws/amazon-kinesis-firehose/config.yml
quickstarts/aws/amazon-linux/config.yml
quickstarts/aws/amazon-mwaa/config.yml
quickstarts/aws/amazon-rds-enhanced/config.yml
quickstarts/aws/aws-lex/config.yml
quickstarts/aws/aws-polly/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-257848
**Description:** Updated "NR1_addData" keyword to quickstarts

Updated "NR1_addData" keyword to quickstarts

---

dashboards/envoy/envoy.json

**Description:** Updated envoy logo URL and about section in envoy dashboard.json

Updated envoy logo URL

---

quickstarts/apache-flink/config.yml
quickstarts/apache-hadoop/config.yml
quickstarts/apache-traffic-server/config.yml
quickstarts/apache-zooKeeper/config.yml
quickstarts/aws/amazon-route53-resolver/config.yml
quickstarts/aws/amazon-security-lake/config.yml
quickstarts/aws/amazon-simpleworkflow/config.yml
quickstarts/aws/amazon-timestream/config.yml
quickstarts/aws/amazon-transfer-family/config.yml
quickstarts/aws/amazon-vpc-lattice/config.yml
quickstarts/aws/amazon-vpc-nat-gateway/config.yml
quickstarts/aws/amazon-workmail/config.yml
quickstarts/aws/amazon-workspaces-web/config.yml
quickstarts/aws/amazon-workspaces/config.yml
quickstarts/aws/aws-rekognition/config.yml
quickstarts/aws/aws-textract/config.yml
quickstarts/aws/aws-translate/config.yml
quickstarts/aws/aws-verified-access/config.yml
quickstarts/java/camel/config.yml
quickstarts/python/amqplib/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-258931
**Description:** Updated 'NR1_addData' keyword to quickstarts

Updated 'NR1_addData' keyword to quickstarts

---

quickstarts/apm-transaction-analysis/config.yaml
quickstarts/apollo/apollo-server/config.yml
quickstarts/argocd/config.yml
quickstarts/atlassian/atlassian-jira/config.yml
quickstarts/aws/aws-appsync/config.yml
quickstarts/aws/aws-certificate-manager/config.yml
quickstarts/aws/aws-chatbot/config.yml
quickstarts/aws/aws-cloudwatch-plugin-for-logs/config.yml
quickstarts/aws/aws-elemental-mediatailor/config.yml
quickstarts/aws/aws-enhanced-monitoring/config.yml
quickstarts/aws/aws-iot-twinmaker/config.yml
quickstarts/aws/aws-lambda-telemetry-extension/config.yml
quickstarts/aws/aws-network-firewall/config.yml
quickstarts/aws/aws-nlb-alb/config.yml
quickstarts/aws/aws-storage-gateway/config.yml
quickstarts/aws/aws-transcribe/config.yml
quickstarts/aws/aws-vpn/config.yml
quickstarts/gcp/apigee-api/config.yml
quickstarts/jira-errors/config.yml
quickstarts/network-monitoring/arista-switches/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-259915
**Description:** Updated 'NR1_addData' to quickstarts

Updated 'NR1_addData' to quickstarts

---

quickstarts/azure/azure-anomaly-detector/config.yml
quickstarts/azure/azure-app-configuration/config.yml
quickstarts/azure/azure-app-gateway/config.yml
quickstarts/azure/azure-app-service-environment/config.yml
quickstarts/azure/azure-app-service-plan/config.yml
quickstarts/azure/azure-application-insights/config.yml
quickstarts/azure/azure-automation-account/config.yml
quickstarts/azure/azure-batch/config.yml
quickstarts/azure/azure-bing-autosuggest/config.yml
quickstarts/azure/azure-bing-custom-search/config.yml
quickstarts/azure/azure-bing-search/config.yml
quickstarts/azure/azure-bing-spell-check/config.yml
quickstarts/azure/azure-bing-web-search/config.yml
quickstarts/azure/azure-cdn-profile/config.yml
quickstarts/azure/azure-cloud-services/config.yml
quickstarts/azure/azure-cognitive-search/config.yml
quickstarts/azure/azure-cognitive-service/config.yml
quickstarts/azure/azure-computer-vision/config.yml
quickstarts/azure/azure-container-registry/config.yml
quickstarts/snowflake/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-261503
**Description:** Updated NR1_addData and NR1_sys keywords

Updated NR1_addData and NR1_sys keywords

---

quickstarts/azure/azure-content-moderator/config.yml
quickstarts/azure/azure-content-safety/config.yml
quickstarts/azure/azure-custom-vision-prediction/config.yml
quickstarts/azure/azure-custom-vision-training/config.yml
quickstarts/azure/azure-data-box-edge/config.yml
quickstarts/azure/azure-data-explorer/config.yml
quickstarts/azure/azure-data-lake-analytics/config.yml
quickstarts/azure/azure-data-lake-storage/config.yml
quickstarts/azure/azure-data-share/config.yml
quickstarts/azure/azure-datafactories/config.yml
quickstarts/azure/azure-device-provisioning-service/config.yml
quickstarts/azure/azure-disk-storage/config.yml
quickstarts/azure/azure-dns-zones/config.yml
quickstarts/azure/azure-event-grid-domains/config.yml
quickstarts/azure/azure-event-grid-partner-namespaces/config.yml
quickstarts/azure/azure-event-grid-partner-topics/config.yml
quickstarts/azure/azure-event-grid-subscriptions/config.yml
quickstarts/azure/azure-event-grid-system-topics/config.yml
quickstarts/azure/azure-event-grid-topics/config.yml
quickstarts/azure/azure-event-hubs/config.yml
quickstarts/azure/azure-face-api/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-263240
**Description:** Updated "NR1_addaData" and "NR1_sys" for quickstarts

Updated "NR1_addaData" and "NR1_sys" for quickstarts

---

quickstarts/ansible-automation-controller/config.yml
quickstarts/audit/pomi-data-ingestion-analysis/config.yaml
quickstarts/notification-channels/servicenow-notifications/config.yml
quickstarts/observability-as-code/pulumi/config.yml
quickstarts/python/psycopg2/config.yml
quickstarts/python/pyelasticsearch/config.yml
quickstarts/python/pymongo/config.yml
quickstarts/quantum-metric/config.yml
quickstarts/rafay/config.yml
quickstarts/redhat/red-hat-enterprise-linux/config.yml
quickstarts/redhat/red-hat-openshift/config.yml
quickstarts/redis-otel/config.yml
quickstarts/redis-prometheus/config.yml
quickstarts/redmine/config.yml
quickstarts/redpanda/config.yml
quickstarts/roku/config.yml
quickstarts/salesforce-eventlog-for-logs/config.yml
quickstarts/sendgrid/config.yml
quickstarts/sendmail/config.yml
quickstarts/shopify/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-264746
**Description:** Updated `NR1_addData` and `NR1_sys` keywords for quickstarts

Updated NR1_addData and NR1_sys keywords for quickstarts

---

quickstarts/fivetran/config.yml

chore: Fix formatting

---

quickstarts/apis/trace/config.yml
quickstarts/node-js/typescript/config.yml
quickstarts/notification-channels/slack-notifications/config.yml
quickstarts/observability-as-code/terraform/config.yml
quickstarts/signl4/config.yml
quickstarts/skykit/config.yml
quickstarts/sonarqube/config.yml
quickstarts/squid-prometheus/config.yml
quickstarts/stripe/config.yml
quickstarts/suse-linux-enterprise-server/config.yml
quickstarts/sybase/config.yml
quickstarts/tidbcloud/config.yml
quickstarts/traefik/config.yml
quickstarts/velero-prometheus/config.yml
quickstarts/video/video-android/config.yml
quickstarts/video/video-chromecast/config.yml
quickstarts/video/video-ios-tvos/config.yml
quickstarts/video/video-web/video-web-akamai/config.yml
quickstarts/video/video-web/video-web-html5/config.yml
quickstarts/video/video-web/video-web-jwplayer/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-264806
**Description:** Updated `NR1_addData` and `NR1_sys` to quickstarts

Updated 'NR1_addData' and 'NR1_sys' to quickstarts

---

quickstarts/dotnet/blazor-server/config.yml
quickstarts/java/camel/config.yml
quickstarts/java/gcp-pubsub/config.yml
quickstarts/java/jdbc-executebatch/config.yml
quickstarts/java/websphere-liberty-profile/config.yml
quickstarts/mean/config.yml
quickstarts/mern/config.yml
quickstarts/mevn/config.yml
quickstarts/php/odbc/config.yml

**Ticket:** https://new-relic.atlassian.net/browse/NR-266930
**Description:** Removed new quickstarts from APM category in SYS and Add Data

Removed keywords for APM category

---

dashboards/kubernetes/kubernetes.json

This PR converts the K8s dashboard to samples instead of dimensional metrics. This was already partly done in this other [PR](https://github.com/newrelic/newrelic-quickstarts/pull/2216), but a few charts were left out.

Convert K8s dashboard back to samples

---

data-sources/aws-cloudfront/config.yml

**Updated the datasource description for aws-cloudfront-logs**
jira: https://new-relic.atlassian.net/browse/NR-255799
shared-component-framework-config repo PR got merged and here is the PR link: https://source.datanerd.us/nr1-dev-experience/shared-component-framework-configs/pull/268
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR …

feat(255799): Updated the datasource description for aws-cloudfront-logs

---

dashboards/biztalk360/biztalk360.json

Added below listed artifacts related default widgets in a page.
Host Instances
Send Ports
Receive Locations
Orchestrations
Suspended Instances
Running Instances

Added artifacts page (Ranjith)

---

data-sources/apache-mesos/config.yml

Updated the datasource description for Apache Mesos
jira: https://new-relic.atlassian.net/browse/NR-288590
shared-component-framework-config repo PR got merged and here is the PR link: https://source.datanerd.us/nr1-dev-experience/shared-component-framework-configs/pull/283

Updated datasource description for Apache mesos

---

data-sources/dbt-cloud/config.yml

This PR changes the data source for dbt Cloud from an install doc to a config, using the config [here](https://source.datanerd.us/nr1-dev-experience/shared-component-framework-configs/tree/master/shared-component/configs/data-sources/dbt-cloud). 

feat(data-source): Migrate to config for dbt Cloud

---

data-sources/linkerd/config.yml

JIRA: https://new-relic.atlassian.net/browse/NR-288609
Install config added for linkerd

Added install config for Linkerd

---

data-sources/envoy/config.yml

JIRA: https://new-relic.atlassian.net/browse/NR-293015
Install config is updated for Envoy

Added install config for envoy

---

data-sources/traceloop/config.yml

data-source id: traceloop
Jira ticket: https://new-relic.atlassian.net/browse/NR-288628

Data source change for traceloop

---

data-sources/vertica/config.yml

JIRA: https://new-relic.atlassian.net/browse/NR-293913

Added datasource for vertica

---

data-sources/temporal-cloud/config.yml

**Jira ticket:** https://new-relic.atlassian.net/browse/NR-293400
**Description:** Updated the datasource install for Temporal cloud. shared-component-framework-config repo PR got merged and here is the PR link: https://source.datanerd.us/nr1-dev-experience/shared-component-framework-configs/pull/315
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not …

Added install config for Temporal cloud

---

data-sources/openstack-controller/config.yml

**Jira ticket:** https://new-relic.atlassian.net/browse/NR-293987
**Description:** Updated the datasource install for Openstack controller. shared-component-framework-config repo PR got merged and here is the PR link: https://source.datanerd.us/nr1-dev-experience/shared-component-framework-configs/pull/316
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you …

Added install config for Openstack controller

---

alert-policies/temporal-cloud/RpsLimit.yml
dashboards/temporal-cloud/temporal-cloud.json
quickstarts/temporal-cloud/config.yml

Temporal asked for a few changes to their quickstart, including adding a new alert, updating the dashboard, and some language fixes on the details.

chore: Minor changes to temporal cloud

---

data-sources/aerospike/config.yml

JIRA: https://new-relic.atlassian.net/browse/NR-294571
Install config added for Aerospike

Added install config for Aerospike

---

data-sources/stripe/config.yml

**Jira ticket:** https://new-relic.atlassian.net/browse/NR-293986
**Description:**  Updated the datasource install for Stripe. shared-component-framework-config repo PR got merged and here is the PR link: https://source.datanerd.us/nr1-dev-experience/shared-component-framework-configs/pull/322
_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an …

Added install config for Stripe

---

dashboards/lambdatest/lambdatest-logs.json

A small fix to match existing field in logs.

stage status fix

---

quickstarts/nr-reports/config.yml

Reverts newrelic/newrelic-quickstarts#2521

Revert "fix: Add data source id to quickstart"

---

dashboards/lambdatest/lambdatest-logs.json

Made some changes to the dashboard queries according to the changes made in data.

LambdaTest: modified queries according to modified data

---

.github/workflows/reusable.build-validate-artifact.yml

chore: Remove inputs from workflow

---

.github/workflows/validate_pr_artifact.yml
data-sources/mobile-getting-started/config.yml

chore: Test change

---

quickstarts/dotnet/blazor-server/config.yml

This section of the docs site was recently refactored this link needs updating. No changes to content.

Fixed dead link in Blazor Server guide

---

_template/data-sources/example-data-source/config.yml
data-sources/windows-certs/config.yml

Remove unsupported markdown content.

Remove markdown syntax from Flex Windows Cert

---

.github/workflows/pr-checks.yml

Changing workflow and adding job names.  We are going to add these jobs as required.

feat: Change workflow and job names

---

data-sources/catchpoint-quickstart/config.yml
data-sources/datazoom/config.yml
data-sources/fastly/config.yml
data-sources/gcp-pubsub/config.yml
data-sources/mongodb-prometheus-integration-docs/config.yml
data-sources/netlify-builds/config.yml
data-sources/netlify-logs/config.yml
data-sources/network-routers-and-switches/config.yml
data-sources/newrelic-cli/config.yml
data-sources/pihole/config.yml
data-sources/sendgrid-integration/config.yml
data-sources/vertx-eventbus/config.yml

https://new-relic.atlassian.net/browse/NR-321974
Shortens the descriptions of the listed data sources.  Many/most of these seem to be duplicates of the quickstart descriptions, so I'm not sure if I should update those to match.

feat: Shorten all data source descriptions to <240 char

---

data-sources/nuxtjs/config.yml

fix(NuxtJS): Update data source

---

dashboards/data-ingest-entity-breakdown/data-ingest-entity-breakdown.json

Updating a link to the new quickstart installation experience.

feat: Update link to link to the correct catalog pack details

---

.github/actions/bootstrap/action.yml

This PR will update github actions cache version to [v4](https://github.com/actions/cache/releases/tag/v4)

chore: Update cache version

---

.github/workflows/yaml-lint.yml

chore: Update checkout version in yaml lint workflow

---

alert-policies/pipeline-control/Errors.yaml
alert-policies/pipeline-control/RequestLatency.yaml

fix: PCG Alerts update operator from ABOVE_OR_EQUALS to ABOVE

---

quickstarts/azure/azure-functions/config.yml

ticket: https://new-relic.atlassian.net/browse/NR-376851
Updated the title

feat: Updated the title

---

alert-policies/browser/AjaxResponseCodes.yml
alert-policies/browser/AjaxThroughput.yml
alert-policies/browser/AjaxTimetoSettle.yml
alert-policies/browser/FirstInputDelay.yml
alert-policies/browser/JSErrors.yml
alert-policies/browser/LargestContentfulPaint.yml
alert-policies/browser/PageloadTime.yml
alert-policies/browser/Throughput.yml
quickstarts/postgresql/config.yml

Release 2025-05-15 (2nd)

---

utils/yarn.lock

fix: Upgrade yarn.lock to resolve vuln issues

---

dashboards/confluent-cloud/confluent-cloud.json

Some changes were made to confluent dashboards related to this [PR](https://github.com/newrelic/newrelic-quickstarts/pull/2652)

feat: NR-411668 Minor changes to confluent dashboard

---

dashboards/confluent-cloud/confluent-cloud.json
utils/yarn.lock

Release 2025-05-29

---

dashboards/ebpf/ebpf.json
quickstarts/ebpf/config.yml

Changes:
- Update eBPF dashboard variable default value
- Update keyword for eBPF quickstart

fix: Update eBPF dashboard and quickstart

---

alert-policies/pipeline-control/CPUUsage.yaml
alert-policies/pipeline-control/DeploymentUnHealthy.yaml
alert-policies/pipeline-control/DropRuleRegistrationFailure.yaml
alert-policies/pipeline-control/ErrorRate.yaml
alert-policies/pipeline-control/Errors.yaml
alert-policies/pipeline-control/MemoryUsage.yaml
alert-policies/pipeline-control/RequestLatency.yaml
alert-policies/pipeline-control/ServiceUnavailability.yaml

No dashboard changes. 
No dashboard changes.
Yes.

More alerts adding with existing PCG alerts

---

dashboards/tidbcloud/dashboard.json
dashboards/tidbcloud/new-dashboard.json

feat: Create new dashboard for tidbcloud

---

dashboards/oma-aqm/alert-quality-management.json

The NRU Alerts Quality Management video recommends removing the `% Investigated` column so this PR does that.
```
We recommend removing the '% Investigated' column, 
from the "Alerting Count by Policy" widget, as its value is always zero.
```
It's currently just blank. 
This PR removes the column.
The reason it is blank or 0 is because the `event` attribute does not always have `acknowledged` as a value
```
filter(count(*), WHERE event = 'acknowledged')/filter(count(*), WHERE event = 'open')*100 AS '% Investigated'
```
Here are 3 months of incidents and the event values.
A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a …

remove % Investigated column

---

dashboards/ebpf/ebpf.json

Update Inbound and Outbound connections in eBPF dashboard.

fix(eBPF): Update Inbound and Outbound connections table

---

dashboards/browser-pages-dashboard/browser_pages_dashboard.json

fix: Sanitize browser pages dashboard
