newrelic/newrelic-quickstarts

- _template/config.yml
I added some more examples to the instrumentation section of the config. Specifically I added an APM example, cloud integration example, and instructions for OHI's and Prometheus exporters.
> feat(_template): added more examples to instrumentation config

- README.md
The file is no longer part of our template. The name and description is taken from the dashboard json.
> fix(docs): removed section that asked to change the config.yaml for dashboard

- packs/couchbase/config.yml
the `logo` value in the couchbase config was previously logo.png, but the logo in the directory is actually logo.svg, so updated that value to reflect what is actually in the directory.
Resolves: https://github.com/newrelic/developer-website/issues/1389
> fix: update couchbase logo filename in config

- CONTRIBUTING.md
This PR gives a contributor some guidelines to consider as the work to submit a new pack or review a PR on an existing pack. It's dependent on our conversation around limitations for the API
> chore: update contributor guide

- docs/config-spec.md
- utils/__tests__/validate_packs.test.js
- utils/schemas/main_config.json
- utils/validate_packs.js
Updates doc and JSON schema for forthcoming pack `documentation` field.
* Held off on URL validation for now as there isn't a great, built-in way to do that in JSON schema. [Regex has it's pitfalls](https://json-schema.org/understanding-json-schema/reference/string.html#index-12) and [this](https://www.stephenlewis.me/notes/json-schema-url-validation/) is closest way I found, which felt like it could hit some snags.
https://github.com/newrelic/newrelic-observability-packs/issues/140
open-install-library-service/pull/56
> Add doc and schema for documentation field

- docs/config-spec.md
- docs/example-schemas/config.json
- docs/install-spec.md
- install/apm/python/install.yml
- install/apm/ruby/install.yml
- install/infrastructure/infra-agent-standard/install.yml
- install/infrastructure/infra-agent-targeted/install.yml
- install/on-host-integration/mysql/install.yml
- packs/infrastructure/config.yml
- utils/schemas/install_config.json
- utils/schemas/main_config.json
- utils/validate_packs.js
Adds schema docs and validation utils for install plans. Also includes an initial set of install plans so we can build out support in the API.
Includes some minor updates to the main_config validation to bring it in line with the API schema.
> feat: add initial install plans

- CONTRIBUTING.md
This PR adds a section to the contributing guide with style tips, and another that adds a general template people can use as an outline for creating a description.
> Fix: Add template and style to contributing guide

- CONTRIBUTING.md
This PR cleans up the contributor guide now that we have autogenerated documentation. I wanted to focus on just calling out some of the nuances of these things, and let the auto gen docs do most of the explaining.
> chore: cleaned up guide

- utils/__tests__/validate_packs.test.js
- utils/schemas/dashboard_config.json
- utils/validate_packs.js
* maintain previous functionality, but add in new functionality to add
instancePath & schemaPath to messages by default. This context will hopefully
point users to specific problematic fields and checks.
* removed redundant condition in schema json.
Previous output:
```sh
Error: packs/mlops/algorithmia/dashboards/algorithmia.json
must be string
must NOT be valid
```
Now:
```sh
Error: packs/mlops/algorithmia/dashboards/algorithmia.json
'/description' must be string
```
Resolves: #324
> improve validation output (for null description of dashboard)

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
- utils/schemas/alert_config.json
- utils/schemas/dashboard_config.json
- utils/schemas/flex_config.json
- utils/schemas/flex_integrations.json
- utils/schemas/logging_config.json
- utils/schemas/main_config.json
- utils/schemas/synthetic_config.json
Update documentation to reference quickstarts rather than observability packs.
> chore: update documentation to reference quickstarts

- .github/workflows/release.yml
Ensure we are always on the latest commit of the `main` branch when generating a release
> fix: explicitly check `main` during release

- quickstarts/nginx/config.yml
Removed a line of the Nginx quickstart description to fit within the length requirements. The copy was restating the header above it, so I figured that would be fine to remove.
> fix: reduce nginx quickstart description length

- install/logs/heroku/install.yml
Reverted Heroku to docs link as we haven't modified the nerdlet yet.
> fix(heroku): reverted to docs only install as nerdlet is out of scope for launch

- utils/schema-doc-generator/script.py
* previously, generated footer also included a timestamp, which would
indicate to git the file was always changing, despite no meaningful
changes to the schema. Stripped the timestamp off the footer to try
and avoid this. Now, git should only see & commit changes if the schema
changes in some meaningful way.
> chore: update script to reword footer

- quickstarts/istio/config.yml
The Istio adapter linked in Quickstarts is no longer supported and the repo has essentially been abandoned.  Newer versions of Istio do not utilize the Istio Mixer and that component has been deprecated as of Istio v1.7.  Istio is currently at v1.11.3.
N/A
N/A
> Marked Istio adapter as deprecated

- quickstarts/apache/config.yml
- quickstarts/dotnet/dotnet/config.yml
- quickstarts/haproxy/config.yml
- quickstarts/infrastructure/config.yml
- quickstarts/java/java/config.yml
- quickstarts/kafka/config.yml
- quickstarts/mysql/config.yml
- quickstarts/nginx/config.yml
- quickstarts/node-js/node-js/config.yml
- quickstarts/php/php/config.yml
- quickstarts/prometheus/config.yml
- quickstarts/python/python/config.yml
- quickstarts/redis/config.yml
- quickstarts/varnish/config.yml
We had some inconsistent capitalization in our description headers. This PR makes them all sentence case, and also makes a few small changes to the sizing of headers (made some h2s -> h3s.)
> fix: sentence-case headers

- .github/workflows/release.yml
Update the release workflow jobs to explicitly pull down git history on the main branch.
Closes #419
> chore: explicit checkout for release

- quickstarts/network-data-ingest-and-cardinality/config.yml
Addressing notes for `Network - Data Ingest and Cardinality` quickstart from Issue #367 by adding a `documentation` section to `config.yml`
> chore: adding docs to config for network data ingest

- quickstarts/codestream/config.yml
Changing the name of the CodeStream quickstart to remove the "New Relic" that was prefixed.  This brings it in-line with the other names.
- [n/a ] Did you check you NRQL syntax? - Does it work?
- [n/a ] Did you check your dashboard image quality? -  Do they look good?
- [n/a ] Did you check that your alerts actually work?
- [n/a ] Did you include an InstallPlan and Documentation reference?
- [n/a ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [n/a ] Did you attach images of your dashboards to the PR so we can see them working?
> fix:  change name and title to CodeStream

- install/aws/aws-cloudwatch-metric-streams/install.yml
- quickstarts/aws/aws-nlb-alb/config.yml
Adding a link-based install plan for AWS dashboards based on CloudWatch metric streams pointing to AWS CloudWatch metric streams setup instructions (no guided install at the moment). 
Starting with ALB dashboard only, we'll migrate others once this is validated. 
> fix: added install plan for aws metric streams dashboards

- quickstarts/account-data-ingestion/config.yml
Just noticed this while querying the API. 
CAUTION: No idea if this YAML change is breaking! Just highlighting the typo really. :D  Feel free to close this PR and address in another way as appropriate
> fix: change typo in quickstart name

- quickstarts/apache/config.yml
Small fix to avoid confusion. Apache is an organization with many different projects, which all have the “Apache” prefix in them. For instance, it’s not “kafka” but “Apache Kafka”, it’s not Cassandra but “Apache Cassandra”.
> fix: small name change to make it clear it's the apache webserver

- CONTRIBUTING.md
"Quick start" --> "Quickstart"
Thought we should be consistent in our contributor guide.
> fix(Quickstarts): Fixed a typo

- quickstarts/macos/config.yml
Apple's official style is `macOS`, not `Mac OS` 
* Our usage guidelines: https://docs.newrelic.com/docs/style-guide/quick-reference/usage-dictionary/#macos
* Example in use on Apple's site: https://www.apple.com/macos/monterey/
> style(macOS): Change `Mac OS` to `macOS`

- install/on-host-integration/cassandra/install.yml
- install/on-host-integration/elasticsearch/install.yml
- install/on-host-integration/haproxy/install.yml
- install/on-host-integration/hashicorp-consul/install.yml
- install/on-host-integration/mongodb/install.yml
- install/on-host-integration/nagios/install.yml
- install/on-host-integration/postgres/install.yml
- install/on-host-integration/rabbitmq/install.yml
- install/on-host-integration/varnish/install.yml
This is removing the targeted installation for OHIs with a high weekly failure rate per this dashboard:
https://staging.onenr.io/0dBj3p0nxQX
Additionally, the documentation links used have been updated to point to the installation instructions section of the given OHI, as the start of the documentation also references the targeted installation command.
> feat: removed OHIs targeted installs with low success rate

- quickstarts/speedscale/config.yml
We no longer use insights insert key, but instead use license keys. Quick copy fix.
> fix: change name of key

- quickstarts/audit/log-ingestion-analysis/config.yml
Fixing the installPlan from guided-install to telemetry-data-platform, because the guided-install does not give the option to skip the installation process.
> fix (logAnalysis): changed installPlan

- install/logs/default/install.yml
- quickstarts/audit/log-ingestion-analysis/config.yml
Adding dedicated install plan for logs; links to default logs management documentation for the `Logs Analysis` dashboard.
> chore: adding default log install plan

- quickstarts/audit/infrastructure-integrations-data-analysis/config.yml
- quickstarts/aws/aws-ecs-ecr/config.yml
- quickstarts/collectd/config.yml
- quickstarts/jmx/config.yml
- quickstarts/mssql/config.yml
- quickstarts/perfmon/config.yml
- quickstarts/postgresql/config.yml
- quickstarts/statsd/config.yml
- Adding keywords so OHIs show up in "infrastructure" category
- Change title of MSSQL to match name in docs https://docs.newrelic.com/docs/infrastructure/host-integrations/get-started/introduction-host-integrations/
This [docs page](https://docs.newrelic.com/docs/infrastructure/host-integrations/get-started/introduction-host-integrations/) links to I/O with the infrastructure category selected, but many OHIs weren't showing up (or in the case of MSSQL, the title didn't match the expected OHI name.
This commit adds the infrastructure keyword to existing keyword lists, and adds keyword lists to quickstarts that were missing them. It also changes the title of MSSQL.
> chore: Show OHIs in infrastructure category

- .github/workflows/run_tests.yml
- .github/workflows/validate_packs.yml
- utils/__tests__/validate_pr_quickstarts.test.js
- utils/validate_pr_quickstarts.js
The functionality we ultimately want to see is that errors relating to install plan id's not existing coming from the api are ignored and don't fail the workflow.
In that effort, I moved handling the graphqlResponses & the handling of this new error case we want into a new method call countErrors(). This method returns the number of errors found, which the caller can still Booleanify to be consumed as before. In the case where we see that error mentioned above, the count is not incremented & the error is effectively ignored. We still print out all errors as before.
Also added in some unit tests.
Resolves: #702
> ignore install plan id does not exist errors

- .github/workflows/validate_install_plans.yml
- utils/__tests__/validate_install_quickstart_plans.test.js
- utils/mock_files/mock-quickstart-5/config.yml
- utils/validate-quickstart-install-plans.js
This PR should resolve the error we were seeing for PR's submitting quickstarts with no install plans. Previously, install plans being missing from the config would cause an error, but is actually a valid quickstart submission.
Also:
* added a unit test for this case.
* updated install plan validation job to use node 16, which lets us use optional chaining & other snazzy additions.
Resolves: #756
> fix for validating quickstarts with no install plans

- utils/__tests__/nr_graphql_helpers.test.js
- utils/instant-observability-categories.json
- utils/nr-graphql-helpers.js
* Remove `featured` keyword to category association. This was causing an
error with validation in the API, since it is not used for that
association.
* Remove `all` category to keyword mapping because it isn't used.
> Fix featured quickstart validation

- .github/workflows/validate_install_plans.yml
- .github/workflows/validate_packs.yml
- utils/__tests__/validate_icon_and_logo.test.js
- utils/nr-graphql-helpers.js
- utils/validate_pr_quickstarts.js
We currently filter out install plan errors we encounter, but still wish to have those logged out. In this instance however, we weren't logging them out 🙈 
With this change, we now log all errors out, including errors relating to install plans not existing.
Output looks like:
```
ERROR: The following errors occurred while validating: quickstarts/elasticsearch/config.yml
- Argument "quickstartMetadata" has invalid value $quickstartMetadata.
In field "summary": Expected type "String!", found null.
ERROR: The following errors occurred while validating: quickstarts/fastly/config.yml
- quickstartMetadata/dashboards/rawConfiguration/pages/widgets/linkedEntityGuids: `linkedEntityGuids` must not be set
- quickstartMetadata/alertConditions/rawConfiguration/terms/operator: `operator` can't be blank …
```
> fix for error logging

- .github/workflows/release.yml
- quickstarts/codestream/teams-cs/config.yml
We moved UUID generation to a new job but it failed on a forked PR. this generates a UUID for the quickstart that slipped through and adds the job back to the release workflow while we debug
> Manually generate UUID

- utils/__tests__/nr_graphql_helpers.test.js
- utils/create-validate-install-plans.js
- utils/create_validate_pr_quickstarts.js
- utils/nr-graphql-helpers.js
- utils/package.json
- utils/yarn.lock
* The concurrency of requests to nerdgraph during validation was
overloading some systems and making us bad users of the api.
* This limits the number of concurrent requests per job to 5
- Closes #777 
- Closes #783
> Limit concurrent requests to nerdgraph

- .github/workflows/release.yml
An artifact of the workflow changes was causing a syntax error in the release workflow, this fixes that.
> remove unneeded workflow dependecy

- utils/create-validate-install-plans.js
- utils/create_validate_pr_quickstarts.js
* Nerdlet state for install plans must be string JSON, it was an object instead
* Update mutations with names for easier future debugging
> Serialize nerdlet state

- utils/__tests__/validate_quickstarts.test.js
- utils/validate_quickstarts.js
* JSON schema validation was mistaking an install plan under a
`/dashboards/` directory for an actual dashboard
* This adds a check for the quickstarts directory when evaluating
related components
> fix: validation pathing

- quickstarts/oma-data-gov/dashboards/data-ingest-baseline.json
Added a 30 day sum chart to the baseline governance dashboard (overview page and all telemetry type breakout pages).
On the overview page the 30 day sum is billboard showing a single number represented the sum of all ingest (in GB) for all accounts and telemetry types.
On the breakout pages the chart is a billboard showing a single number for the 30 day gb ingest sum for a single telemetry type (for all accounts).
- [✅ ] Did you check you NRQL syntax? - Does it work?
- [ ✅] Did you check your dashboard image quality? -  Do they look good?
- [NA ] Did you check that your alerts actually work?
- [ NA] Did you include an InstallPlan and Documentation reference?
- [ ✅] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ✅] Did you attach images of your …
> feat: add 30 day sum billboard chart

- CONTRIBUTING.md
- install/on-host-integration/ibm-mq/install.yml
- install/third-party/databricks/install.yml
- install/third-party/trendmicro-cloudone-conformity/install.yml
- quickstarts/grafana/grafana-dashboard-migration/config.yml
- quickstarts/mlops/bring-your-own/config.yml
- quickstarts/netlify/config.yml
This PR sets the correct support levels on quick starts referencing experimental projects. 
It also updates he contributor guide to more explicitly explain the levels.
> fix: sets community levels updates contributing doc

- .github/workflows/pr-merged.yml
- .github/workflows/release.yml
To enforce the validations passing, we are adding them as required steps for merging into main. Previously, there were none. Adding them manually to the repo also doesn't work since code in the workflows resets them, so we updated the workflow code.
> chore: update branch protection steps with required checks

- .github/workflows/pr-merged.yml
The changes made were:
* first change was moving the commit step closer to the push step in
the overall workflow. Now, branch protection happens first, then commit,
then push. This should reduce the time between commit and push.
* second change was adding a pull command before changes are committed.
This should tighten the window of this step failing due a change
to main in main not being pulled, before we try to push local changes.
* the last change is grouping the echo command in the commit step with
the commit command. Now, echo setting the output should only happen when
we have changes to commit. If we dont have any changes, echo shouldnt
occur, and the push step should not run.
Relates to: #862
> update commit, push steps to reduce errors

- utils/__tests__/validate_pr_quickstarts.test.js
- utils/create_validate_pr_quickstarts.js
We realized that the support level behind the scenes was always set to `Community` regardless of how it was configured in the quickstart. Because we rely on this value to determine the "verified" icon, we added support for a `supportLevel` argument when submitting a quickstart. This PR adds support for sending the configured support level.
> Send support level when submitting a quickstart

- CONTRIBUTING.md
This PR adds the guideline of providing a unique name to a dashboard's json file and how to check if there are any duplicate dashboard names. This PR must be merged before [PR 848](https://github.com/newrelic/newrelic-quickstarts/pull/848)
> Add Dashboard Name Uniqueness Rule to ReadMe

- utils/package.json
Moves all dependencies out of dev dependencies so they will still be installed when `NODE_ENV` is set to `production`
> move deps out of dev

- quickstarts/speedscale/dashboards/speedscale-reports.json
This PR removed entity IDs, from the dashboard json as it was blocking this PR https://github.com/newrelic/newrelic-quickstarts/runs/5415786835?check_suite_focus=true
It also lints the JSON
> chore: removed entity ids from json

- quickstarts/ruby/rails/config.yml
The Rails quickstart is missing some screenshots on the catalogs. This is a quick PR to trigger the publishing workflows to get those screenshots into the database.
> fix: newline change to trigger publish

- quickstarts/catchpoint/config.yml
- quickstarts/gigamon/config.yml
- quickstarts/glassbox/config.yml
- quickstarts/golang/pkg-errors/config.yml
- quickstarts/jumpstart/config.yml
- quickstarts/oma-aqm/config.yml
- quickstarts/python/aiohttp/config.yml
- quickstarts/python/bottle/config.yml
- quickstarts/python/celery/config.yml
- quickstarts/python/django/config.yml
- quickstarts/python/facepy/config.yml
- quickstarts/python/fastapi/config.yml
- quickstarts/python/feedparser/config.yml
- quickstarts/python/flask/config.yml
- quickstarts/python/gevent/config.yml
- quickstarts/python/httplib2/config.yml
- quickstarts/python/mako/config.yml
- quickstarts/python/pylibmc/config.yml
- quickstarts/python/pyramid/config.yml
- quickstarts/python/tornado/config.yml
- quickstarts/python/twisted/config.yml
- quickstarts/python/web2py/config.yml
- quickstarts/python/webpy/config.yml
- quickstarts/ruby/net-http/config.yml
This PR fixes numerous problems with quickstarts including:
- misc typos and line formatting issues
- titles that should be sentence case
- removes "quickstarts" from titles as it's redundant
> Misc quickstart fixes

- quickstarts/netlify/config.yml
this PR sets the name of netlify builds back to netlify due to the issue without having a good way to handle URL redirects for name changes on the I/O site.
> fix: renames netlify qs due to 404 url issue

- quickstarts/gigamon/config.yml
To ensure the URL isn't broken for Gigamon, on the I/O site I'm reverting the title to match the name until we resolve #957 
```
Previous: 'https://newrelic.com/instant-observability/gigamon-newrelic/d6b36ecf-bf99-475c-938f-370153db8e70'
Now: 'https://newrelic.com/instant-observability/gigamon/d6b36ecf-bf99-475c-938f-370153db8e70'
```
> fix: changes name to match title for URL consistency

- quickstarts/gigamon/config.yml
After talking to DevEx this should get gigamon's URL back to the proper state.
> fix: changes title for slugification

- utils/__tests__/validate_install_quickstart_plans.test.js
- utils/validate-quickstart-install-plans.js
The `Validate install plan ids` workflow was failing when a quickstart was deleted as part of the pull request. That was because it tried to read a file that doesn't exist. These changes filter out files with the status of `removed` from the Github API response before the files are read from the filesystem.
Full integration test on my fork [here](https://github.com/aswanson-nr/newrelic-quickstarts/pull/18)
Closes #749
> fix: handle when quickstarts are removed

- .github/workflows/validate_install_plans.yml
* with multi line blocks, needed the pipe operator. Previously, this
step was always passing despite failures that should have been occurring
during validation.
Relates to: #995
> fix install plan validation

- utils/sanitize_dashboards.js
We had an issue get through for a newly created dashboard, where the sanitize-dashboard script was removing commas within NRQL. It is only supposed to remove trailing slashes from the dashboard JSON. Looks like the regex for removing trailing commas is picking up the `),` in the NRQL. I tested removing `\)` from this [regex]( https://github.com/newrelic/newrelic-quickstarts/blob/main/utils/sanitize_dashboards.js#L16) and that seemed to do the trick. I can’t think of any situations where we would need to remove a trailing comma after a closing parentheses in json, so this seems like a change worth making.
> Fix NRQL parsing in sanitize dashboard script

- install/apm/dotnet/multi-os/install.yml
- install/apm/dotnet/windows-only/install.yml
- install/apm/php/targeted-install/install.yml
- install/on-host-integration/apache/install.yml
- install/on-host-integration/cassandra/install.yml
- install/on-host-integration/couchbase/install.yml
- install/on-host-integration/elasticsearch/install.yml
- install/on-host-integration/haproxy/install.yml
- install/on-host-integration/hashicorp-consul/install.yml
- install/on-host-integration/jmx/install.yml
- install/on-host-integration/kafka/install.yml
- install/on-host-integration/memcached/install.yml
- install/on-host-integration/mongodb/install.yml
- install/on-host-integration/mssql/install.yml
- install/on-host-integration/mysql/install.yml
- install/on-host-integration/nagios/install.yml
- install/on-host-integration/nginx/install.yml
- install/on-host-integration/postgres/install.yml
- install/on-host-integration/rabbitmq/install.yml
- install/on-host-integration/redis/install.yml
- install/on-host-integration/varnish/install.yml
This PR contains changes to fix the [recent workflow failure](https://github.com/newrelic/newrelic-quickstarts/runs/5779399220?check_suite_focus=true) we saw. The particular errors are install plans having a `target.context` field, and the `target.type` value we submit to the API -- `ON-HOST-INTEGRATION` -- being incorrect.
Changes:
* remove `target.context` field
* change `target.type` value of `on-host-integration` to `on_host_integration`
Resolves: #995
> fixup broken install plans

- quickstarts/kubernetes/coredns/alerts/coredns-panics.yml
The `coredns-panics` alert on the CoreDNS quickstart was throwing errors during installation. This was do to not having the `expirationDuration` set. 
After this is merge, the alerts should install without issue.
> Add expirationDuration to coredns alert

- utils/sanitize_dashboards.js
After rebasing with upstream main, I noticed the dashboard directory structure changed and I was getting an error when running the sanitize script. My goal was to update the script to work with the new structure while continuing to work with the old. It merges any `.json` files found in nested directories under the top directory (only 1 level down). For example, `./kubernetes/coredns/` will check 
- `./kubernetes/coredns/` itself for `.json` files
- `./kubernetes/coredns/coredns-dashboard` for `.json` files
and merge results together.
> Updating sanitize dashboards script for nested dashboards

- quickstarts/kubernetes/kubernetes/dashboards/kubernetes/kubernetes.json
Chart is currently showing all container with restarts despite if it happened in the timewindow selected, this also makes that the reason for the restarts appears empty .
This filter will avoid showing restarts that happened outside the time window, and because of that it will always show the latest restart reason.
> fix: k8s dashboard restart chart

- quickstarts/golden-signals-web/config.yml
* Move golden signals to the targeted infrastructure install plan
* This will allow user's to skip the installation if they already have
their software monitored
> fix: update golden signals to new install

- data-sources/trendmicro-cloudone-conformity/config.yml
After further discussion, we want to remove the `Trend Micro` data source from the AWS category. We'll leave it in `Partner` for now.
> Remove Trend Micro from AWS category

- .github/workflows/preview-links.yml
- utils/__tests__/create-preview-links.test.ts
- utils/__tests__/helpers.test.js
- utils/__tests__/test-utilities.js
- utils/__tests__/validate_pr_quickstarts.test.js
- utils/constants.ts
- utils/create-preview-links.ts
- utils/create_validate_pr_quickstarts.ts
- utils/helpers.ts
- utils/package.json
* Adds a workflow to generate links for pull request previews
* Adds script to create the links using the github API
* Moved some helper functions out of quickstart validation and into the general `helpers.ts`
- [1 quickstart](https://github.com/aswanson-nr/newrelic-quickstarts/pull/23)
- [3 quickstarts](https://github.com/aswanson-nr/newrelic-quickstarts/pull/25)
- [no quickstarts](https://github.com/aswanson-nr/newrelic-quickstarts/pull/24)
> Generate pull request preview links

- utils/preview.ts
PR switches URLs from `localhost:8000` to `newrelic.com/instant-observability`
We will merge this once we have the feature branch on I/O in production
> Switch preview URL to production URL

- .gitignore
- utils/create-quickstarts-snapshot.ts
Adds a script that creates a JSON file in a (git ignored) `snapshots/` directory for _each_ quickstart. We can use these snapshots to ensure that we haven't accidentally mutated any of the quickstarts while moving files around.
To run (from the `utils/` directory):
```sh
$ npx ts-node create-quickstart-snapshots.ts
```
- NR-14162
> Script to create Quickstart mutation snapshots

- utils/migration_scripts/move-alerts.ts
Creates a script that does the following:
1. Creates a new `alert-policies/` top-level directory
2. Creates a sub-directory for every quickstart _that has at least one alert condition_
3. Updates the quickstart configurations to reference those directories
4. Removes the old `alerts/` directory in each quickstart
This PR is just for the _script_ that updates this stuff. We'll want to move the content when the rest of this epic is complete.
- NR-14177
> Migration script for alert policies

- install/third-party/chef/install.yml
- quickstarts/observability-as-code/chef/config.yml
Here for “chef quickstart” shows See Installation docs , so for that I have added install plans (third-party-chef) then it can redirect to signup-page before seeing the installation docs. Added “chef” folder in third-party and also added install plans in chef config.yml file.
> NR-20560 Added install plans for chef

- install/third-party/amazon-eks-on-aws-fargate/install.yml
- quickstarts/aws/amazon-eks-on-aws-fargate/config.yml
Here for “Amazon EKS on AWS Fargate quickstart” shows See Installation docs , so for that I have added install plans (third-party-amazon-eks-on-aws-fargate) then it can redirect to signup-page before seeing the installation docs. Added “amazon-eks-on-aws-fargate” folder in third-party and also added install plans in amazon-eks-on-aws-fargate config.yml file.
> chore(Amazon EKS on AWS Fargate): Added install plans

- install/third-party/sagemaker/install.yml
- quickstarts/mlops/sagemaker/config.yml
Here for “amazon-sagemaker quickstart” shows See Installation docs , so for that I have added install plans (third-party-amazon-sagemaker) then it can redirect to signup-page before seeing the installation docs. Added “sagemaker” folder in third-party and also added install plans in sagemaker config.yml file.
> chore(sagemaker): Added install plans

- install/third-party/apigee-api/install.yml
- quickstarts/gcp/apigee-api/config.yml
Here for “Apigee API quickstart” shows See Installation docs , so for that I have added install plans (third-party-apigee-api) then it can redirect to signup-page before seeing the installation docs. Added “apigee-api” folder in third-party and also added install plans in apigee-api config.yml file.
> chore(apigee api): Added install plans

- install/third-party/aws-firelens-plugin-for-logs/install.yml
- quickstarts/aws/aws-firelens-plugin-for-logs/config.yml
Here for “AWS FireLens plugin for Logs quickstart” shows See Installation docs , so for that I have added install plans (third-party-aws-firelens-plugin-for-logs) then it can redirect to signup-page before seeing the installation docs. Added “aws-firelens-plugin-for-logs” folder in third-party and also added install plans in aws-firelens-plugin-for-logs config.yml file.
> chore(AWS-FireLens-plugin-for-Logs): Added install plans for AWS FireLens plugin for Logs

- install/third-party/aws-cloudwatch-plugin-for-logs/install.yml
- quickstarts/aws/aws-cloudwatch-plugin-for-logs/config.yml
Here for “AWS Cloudwatch plugin for Logs quickstart” shows See Installation docs , so for that I have added install plans (third-party-aws-cloudwatch-plugin-for-logs) then it can redirect to signup-page before seeing the installation docs. Added “aws-cloudwatch-plugin-for-logs” folder in third-party and also added install plans in aws-cloudwatch-plugin-for-logs config.yml file.
> chore(AWS-Cloudwatch-plugin-for-Logs): Added install plans for AWS Cloudwatch plugin for Logs

- install/third-party/jira-errors/install.yml
- quickstarts/jira-errors/config.yml
Here for “Atlassian jira for errors inbox quickstart” shows See Installation docs , so for that I have added install plans (third-party-jira-errors-inbox) then it can redirect to signup-page before seeing the installation docs. Added “jira-errors” folder in third-party and also added install plans in jira-errors config.yml file.
> refactor(Atlassian-jira-for-errors-inbox): Added install plans for Atlassian jira for errors inbox

- install/third-party/ads-web-gpt/install.yml
- quickstarts/ads/web/ads-web-gpt/config.yml
Here for “Google Publisher Tags inbox quickstart” shows See Installation docs , so for that I have added install plans (third-party-ads-web-gpt) then it can redirect to signup-page before seeing the installation docs. Added “ads-web-gpt” folder in third-party and also added install plans in ads-web-gpt config.yml file.
> Added install plans to Google Publisher Tags

- install/third-party/collectd/install.yml
- quickstarts/collectd/config.yml
Here for “CollectD quickstart” shows See Installation docs , so for that I have added install plans (third-party-collectd) then it can redirect to signup-page before seeing the installation docs. Added “collectd” folder in third-party and also added install plans in collectd config.yml file.
> Added install plans for CollectD

- utils/package.json
Mistakenly changed this script to run .ts converted back to .js extension
> Change generate-schema-docs script back to .js extension

- install/third-party/user-flow/install.yml
- quickstarts/synthetics/user-flow/config.yml
Here for “Synthetics User Flow check quickstart” shows See Installation docs , so for that I have added install plans (third-party-synthetics-user-flow) then it can redirect to signup-page before seeing the installation docs. Added “user-flow” folder in third-party and also added install plans in user-flow config.yml file.
> Added install plans for Synthetics User Flow check

- install/third-party/unix/install.yml
- quickstarts/unix/config.yml
Here for “Unix quickstart” shows See Installation docs , so for that I have added install plans (third-party-unix) then it can redirect to signup-page before seeing the installation docs. Added “unix” folder in third-party and also added install plans in unix config.yml file.
> Added install plans for Unix

- install/third-party/oma-aqm/install.yml
- quickstarts/oma-aqm/config.yml
Here for “Alert Quality Management quickstart” shows See Installation docs , so for that I have added install plans (third-party-alert-quality-management) then it can redirect to signup-page before seeing the installation docs. Added “oma-aqm” folder in third-party and also added install plans in oma-aqm config.yml file.
> Added install plans for Alert Quality Management

- install/third-party/oma-bofu/install.yml
- quickstarts/oma-bofu/config.yml
Here for “Customer Experience Bottom of the funnel analysis quickstart” shows See Installation docs , so for that I have added install plans (third-party-oma-bofu) then it can redirect to signup-page before seeing the installation docs. Added “oma-bofu” folder in third-party and also added install plans in oma-bofu config.yml file.
> Added install plans for Customer Experience Bottom of the funnel analysis

- install/third-party/victorops/install.yml
- quickstarts/victorops/config.yml
Here for “victorops quickstart” shows See Installation docs , so for that I have added install plans (third-party-victorops) then it can redirect to signup-page before seeing the installation docs. Added “victorops” folder in third-party and also added install plans in victorops config.yml file.
> Added Installplans for victorops

- install/third-party/cli/install.yml
- quickstarts/observability-as-code/cli/config.yml
Here for “New Relic CLI quickstart” shows See Installation docs , so for that I have added install plans (third-party-cli) then it can redirect to signup-page before seeing the installation docs. Added “cli” folder in third-party and also added install plans in cli config.yml file.
> Added install plans for New Relic CLI

- install/third-party/port-monitoring/install.yml
- quickstarts/port-monitoring/config.yml
Here for “Port monitoring quickstart” shows See Installation docs , so for that I have added install plans (third-party-port-monitoring) then it can redirect to signup-page before seeing the installation docs. Added “port-monitoring” folder in third-party and also added install plans in port-monitoring config.yml file.
> Added install plans for Port monitoring

- install/third-party/camel/install.yml
- quickstarts/java/camel/config.yml
Here for “Apache Camel java agent extension quickstart” shows See Installation docs , so for that I have added install plans (third-party-camel) then it can redirect to signup-page before seeing the installation docs. Added “ camel” folder in third-party and also added install plans in camel config.yml file.
> refactor(Camel): Added install plans for apache camel java agent extension

- install/third-party/video-android/install.yml
- quickstarts/video/video-android/config.yml
Here for “Video agent for android quickstart” shows See Installation docs , so for that I have added install plans (third-party-video-android) then it can redirect to signup-page before seeing the installation docs. Added “video-android” folder in third-party and also added install plans in video-android config.yml file.
> refactor(Video-android): Added install plans for video agent for android

- install/third-party/split/install.yml
- quickstarts/split/config.yml
Here for “Split quickstart” shows See Installation docs , so for that I have added install plans (third-party-split) then it can redirect to signup-page before seeing the installation docs. Added “split” folder in third-party and also added install plans in split config.yml file.
> refactor(Split): Added install plans for split

- install/third-party/signl4/install.yml
- quickstarts/signl4/config.yml
Here for “SIGNL4 quickstart” shows See Installation docs , so for that I have added install plans (third-party-signl4) then it can redirect to signup-page before seeing the installation docs. Added “signl4” folder in third-party and also added install plans in signl4 config.yml file.
> refactor(SIGNL4): Added install plans for signl4

- .github/workflows/preview-links.yml
* Moves the pull request url, pull request number, and generated comment into environment variables to prevent command injection
> fix: move input into env variables

- utils/lib/Quickstart.ts
- utils/preview.ts
Small update to quickstart class to help for cleaner error parsing.
This came up with fixing a bug in local quickstart preview
```bash
jgregory$ yarn preview dotnet
yarn run v1.22.19
$ ts-node preview.ts dotnet
Unable to parse quickstart config /Users/jgregory/Developer/newrelic-external/newrelic-quickstarts/quickstarts/dotnet/ Error: EISDIR: illegal operation on a directory, read
at Object.readSync (node:fs:727:3)
at tryReadSync (node:fs:433:20)
at Object.readFileSync (node:fs:479:19)
at Quickstart.getConfigContent (/Users/jgregory/Developer/newrelic-external/newrelic-quickstarts/utils/lib/Quickstart.ts:97:31)
at new Quickstart (/Users/jgregory/Developer/newrelic-external/newrelic-quickstarts/utils/lib/Quickstart.ts:76:24)
at validateArgs …
```
> Update error handling for Quickstart class

- utils/create_validate_pr_quickstarts.ts
The check for invalid components was adding valid quickstarts to the array of invalid ones, this reverses that logic to work as we expected.
> Fix quickstart submission logic

- quickstarts/node-js/node-js/config.yml
Adds some more variations of `node.js` to the Node.js quickstart keyword list to improve search results.
> Add keywords for Node.js

- dashboards/mssql-queryplan/mssql-queryplan.json
As the referenced custom viz requires manual deploy, this widget was causing a 404 error.
> fix: [mssql-queryplan] remove reference to custom visualization

- install/on-host-integration/hashicorp-consul/install.yml
- install/on-host-integration/mongodb/install.yml
- install/on-host-integration/postgres/install.yml
- install/on-host-integration/rabbitmq/install.yml
Re-enable CLI install for Postgres, RabbitMQ, MongoDB, Consul after recipe refactor.
> chore: Re-enable CLI install for Postgres, RabbitMQ, MongoDB, Consul

- install/aws/aws-vpc-flow-logs/install.yml
- quickstarts/aws/aws-vpc-flow-logs/config.yml
We [released](https://newrelic.com/blog/nerdlog/amazon-vpc-flow-logs) a new capability for our AWS VPC Flow Logs integration today and need to update the quickstart to use the in-product setup wizard. I've added a _new_ install plan that points to our setup wizard (with a fallback to docs) as well as updated some of the language and documentation links.
> fix(vpc): update VPC Flow Logs to use new install plan

- quickstarts/etcd/config.yml
- utils/create_validate_pr_quickstarts.ts
A bug in our error processing from nerdgraph caused errors to be dropped instead of printed to the console. This fixes that issue and updates the Etcd quickstart with a correct slug.
> Fix error output and update Etcd slug

- utils/__tests__/create-validate-pr-quickstarts.test.js
- utils/create_validate_pr_quickstarts.ts
Some logic to ignore install plan step id errors was lost, this re-adds it.
These errors occur when a new quickstart is created along with its install plan because the database has no idea that the install plan is part of the PR.
> Properly ignore installPlanStepId errors

- utils/__tests__/create-validate-pr-quickstarts.test.js
- utils/create-validate-data-sources.ts
- utils/create-validate-install-plans.ts
- utils/create_validate_pr_quickstarts.ts
- utils/dashboard-helper.ts
- utils/lib/github-api-helpers.ts
- utils/validate-quickstart-install-plans.ts
Removed files were not being filtered out during validation, which can cause errors when the scripts attempt to read the file on disc.
This updates the logic for quickstart, install plan, and data-source validation.
> Filter out removed files during PR validation

- _template/alert-policies/example-alert-policy/baseline-alert.yml
- _template/alert-policies/example-alert-policy/static-alert.yml
Our template alerts had a `---` yaml document separator at the top, this allows you to define multiple "documents" per yaml file. We do not support this for alerts and require that there is one alert condition per file.
> Remove yaml document separators from template alerts

- quickstarts/harbor/config.yml
The Harbor quickstart is missing an authors field, this adds one.
> Update Harbor quickstart with author field

- _template/quickstarts/example-quickstart/config.yml
The quickstart template was using an incorrect field for alerts, this updates it to the correct field name.
> Quick fix for the quickstart template

- dashboards/calico/calico.json
Deleted local tags widget 
As per latest Calico source code, this metric has been deleted.
https://github.com/projectcalico/calico/commit/46c954f21ca5057a50afed0ee94f81737107082a#diff-c98e45a80bc6858972684cf22e5007c61169de0475ee52e95309599eecfcdb9fL24
> Deleted local tags widget from calico

- install/pomi/install.yml
Updating the description for the `setup-pomi` install plan to drop K8s support and make it Docker-only.
Updating the description for the `setup-pomi` install plan.
> Update description for setup-pomi

- alert-policies/coredns/coredns-error-rate.yml
- alert-policies/coredns/coredns-panic-rate.yml
- alert-policies/coredns/coredns-request-duration.yml
- alert-policies/coredns/coredns-request-rate.yml
Alerts were erroring on import due to invalid `fillOption`.
> fix fillOption for CoreDNS alerts

- alert-policies/prometheus-agent/DupMetrics.yml
- quickstarts/prometheus-agent/config.yml
Due to a new version of the integrations filters, a target that was already scaped by a different job is scraped again. 
In order to prevent that and be notified in case of duplicated data, you can create an alert based on the following query:
```
FROM Metric select uniqueCount(job) facet instance, cluster_name limit 10 since 2 minutes ago
```
If any value is different from 1 then you have two or more jobs scraping the same instance in the same cluster.
https://github.com/newrelic/docs-website/pull/10553/files
> feat(prom-agent): duplicated data alert

- dashboards/redis-prometheus/redis-prometheus.json
Prometheus Redis Dashboard: Modify _redis_connected_clients_(GAUGE) queries to use MAX instead of SUM.
> Prometheus Redis Dashboard modify redis_connected_clients(GAUGE) queries [NR-75171]

- .github/workflows/reusable.quickstart_submission.yml
- utils/package.json
The latest run of "Update quickstarts" [failed](https://github.com/newrelic/newrelic-quickstarts/actions/runs/3851426408/jobs/6562606655). No need to rerun it since the PR that kicked it off had no content changes.
Looks like we are missing some scripts in the `package.json` for the new workflows, I added those and fixed a typo.
> Add script aliases and fix typo

- utils/data-source-from-install-plan.ts
- utils/lib/DataSource.ts
- utils/types/DataSourceConfig.ts
- utils/types/DataSourceMutationVariable.ts
- utils/types/InstallPlanConfig.ts
> Script to create a new data sources from install plans

- .github/workflows/pr-merged.yml
- .github/workflows/preview-links.yml
- .github/workflows/release.yml
- .github/workflows/validate_data_sources.yml
- .github/workflows/validate_install_plans.yml
- .github/workflows/validate_packs.yml
- quickstarts/apache/config.yml
- utils/__tests__/create-preview-links.test.ts
- utils/__tests__/dashboard-helper.test.js
- utils/create-preview-links.ts
- utils/dashboard-helper.ts
- utils/package.json
- utils/yarn.lock
https://issues.newrelic.com/browse/NR-88402
In typescript files, the github doc recommends upgrading @actions/core to v1.10.0 and using the toolkit functions directly to set environment variables via core.setOutput.  This is much better than what i originally did, which was to change the return of the scripts to output the values we need.
> Update github actions to remove set-output usage

- .github/workflows/pr-merged.yml
env is not available in this place, so using the value from outputs.
> fix: remove env call from pr-merged

- quickstarts/core-web-vitals/config.yml
The job to publish the latest changes to this quickstart failed due to issues in the pipeline. Those issues have been addressed and this PR is to trigger them again for the `core-web-vitals` quickstart to get those changes published.
> Trigger new build for core-web-vitals

- dashboards/mongodb-prometheus/mongodb.json
This PR fixes queries for populating variables which in case customers have a lot of information wouldn't be populated correctly as the default query limit is 10 results.
It also adds a `since 1 day ago` to all variable queries to match the expiration period of mongo entities
> Fix mongodb prometheus dashboard limits (NR-105374)

- data-sources/openai/config.yaml
- quickstarts/openai/config.yaml
This PR switches to showing the openai quickstart in Add data and Select your stack over the data source
> chore: Favor showing openai qs in add data

- utils/__tests__/create-validate-pr-quickstarts.test.js
- utils/__tests__/dashboard-helper.test.js
- utils/__tests__/set-dashboard-required-datasources.test.js
- utils/dashboard-helper.ts
The dashboard helper was outputting comments that were unreadable because the newlines were not being respected.
This appears to be due to us using the `actions/core` library to handle setting the output, we no longer need to use the encoded newline and can just make use of `\n` directly.
> Fix dashboard helper output

- quickstarts/azure/azure-app-service-environment/config.yml
- quickstarts/azure/azure-app-service-plan/config.yml
- quickstarts/azure/azure-application-insights/config.yml
- quickstarts/azure/azure-automation-account/config.yml
- quickstarts/azure/azure-cdn-profile/config.yml
- quickstarts/azure/azure-cloud-services/config.yml
- quickstarts/azure/azure-cognitive-search/config.yml
- quickstarts/azure/azure-data-box-edge/config.yml
- quickstarts/azure/azure-data-explorer/config.yml
- quickstarts/azure/azure-data-lake-analytics/config.yml
- quickstarts/azure/azure-data-lake-storage/config.yml
- quickstarts/azure/azure-data-share/config.yml
- quickstarts/azure/azure-device-provisioning-service/config.yml
- quickstarts/azure/azure-hdinsight/config.yml
- quickstarts/azure/azure-integration-service-environment/config.yml
- quickstarts/azure/azure-iot-hub/config.yml
- quickstarts/azure/azure-netapp-capacity-pools/config.yml
- quickstarts/azure/azure-netapp-files/config.yml
- quickstarts/azure/azure-notification-hubs/config.yml
- quickstarts/azure/azure-peering-service/config.yml
- quickstarts/azure/azure-peering/config.yml
- quickstarts/azure/azure-private-dns-zones/config.yml
- quickstarts/azure/azure-purview/config.yml
- quickstarts/azure/azure-spring-apps/config.yml
- quickstarts/azure/azure-stream-analytics/config.yml
- quickstarts/azure/azure-synapse-analytics/config.yml
- quickstarts/azure/azure-time-series-insights/config.yml
- quickstarts/azure/azure-web-apps/config.yml
@glennthomas1 had previously created a bunch of Azure-based quickstarts: #1790 
Unfortunately, our workflows did not properly run when that PR was merged: the "submit gate" was never run, which meant that the "update quickstarts" workflow (which does the actual submission) wasn't run.
This PR attempts to trigger the workflow again by making a small adjustment to each of those files (necessary to be included in the upload). All I've done is move the `title` field towards the top of the config file. It's possible that my editor's linter cleaned up a few whitespace discrepancies, but no content has been altered.
> Update Azure-based quickstarts that failed to submit previously

- CONTRIBUTING.md
- utils/preview.ts
* Updates the preview url to be localhost while support is built in to the new production site.
> Update preview link to local

- CONTRIBUTING.md
It seems that viewing quickstarts locally is no longer possible via the steps we noted in the docs. Updated the docs to reflect this.
> Deprecate "local quickstart preview" docs

- quickstarts/redmine/config.yml
Added a keywords of redmine quickstart in Add data and Stack page.
NR1_addData
NR1_sys
https://issues.newrelic.com/browse/NR-151504
> Adding a keyword of Redmine quickstart into a Add Data and Stack page

- dashboards/kubernetes/kubernetes.json
Fixes https://issues.newrelic.com/browse/NR-143803. 
A user is seeing the following error for multiple widgets in the Kubernetes Quickstart dashboard:
`We tried to transform your Metric query into a query that is compatible with the previous Infrastructure metric format. The transformation was cancelled because it would result in an oversize query. ` 
This error is because the shimming could not make a transformation of the query. By adding the `metricName` filter, we can tell the transformation which sample table to look at.
> fix(Kubernetes Dashboard): fix query transformation errors

- quickstarts/delphix/config.yml
The Delphix team updated our documentation links. This PR exists solely to fix the broken link.
> Update Delphix Doc Link

- .github/workflows/pr-merged.yml
- .github/workflows/release.yml
- .github/workflows/validate_packs.yml
- utils/validate-quickstart-data-sources.ts
We had previously implemented a script to check if a data source referenced in a quickstart actually exists. This script never made it into a workflow and wasn't being run on pull requests, this PR adds a job to run this script and updates some of the error output.
> Properly validate data source id references on quickstarts

- .github/workflows/pr-merged.yml
- .github/workflows/release.yml
- .github/workflows/submit-gate.yml
Now that pull requests are going into the `release` branch, we need to generate quickstart ids at that time instead when they are merged into the `main` branch. This ensures that the `release` branch stays ahead or even with `main`. 
Also updates the required checks to be accurate.
> fix: Target `release` and update checks

- utils/lib/Alert.ts
- utils/lib/__tests__/Alert.test.js
- utils/lib/__tests__/Quickstart.test.js
- utils/mock_files/alert-policies/mock-alert-policy-3/errors.yml
- utils/mock_files/quickstarts/mock-quickstart-6/config.yml
This PR stems from handling alert policy error while installing alerts in our UI.
We found that alert conditions that contain a nrql query with `TIMESERIES` fail an installation after it 
hits our database.
This is a supplementary PR #2190 so we can have a more automated process when verifying alert conditions in PRs.
Our workflows that validate quickstarts will fail during checks.
Testing PR: https://github.com/newrelic/newrelic-quickstarts/pull/2197
- This PR should fail
Link to validation failure + logs: https://github.com/newrelic/newrelic-quickstarts/actions/runs/7468258398/job/20323336084
> Note: as of right now, we have 3 other alerts containing invalid queries, so it is a little noisy in the logs
> Update Alert class to handle nrql validation

- utils/create_validate_pr_quickstarts.ts
- utils/lib/Alert.ts
- utils/set-alert-policy-required-datasources.ts
- utils/set-dashboards-required-datasources.ts
* Reducing the number of requests that run at a time to avoid race conditions in the API. 
* Filter out test/mock files
* Update alert validation to look for the `TIMESERIES` keyword not just the word `timeseries`
> Some fixes to the release script

- quickstarts/apdex-optimizer/config.yml
This quickstart got lost in the November shuffle, this change is just to get it picked up by the publishing process.
> Newline change to trigger publishing

- data-sources/nvidia-dcgm/config.yml
There is a [quickstart that has the same keyword](https://github.com/newrelic/newrelic-quickstarts/blob/a8b5d32e7c159694104fa7c6a0babe676343b8fc/quickstarts/nvidia-dcgm/config.yml#L41), the keyword should not be on both data source and quickstart that uses the data source. This PR removes the data source keyword.
> feat(NVIDIA): Remove keyword

- quickstarts/mosaicml/config.yml
Removes the keyword associated with the "ML Models" category.
> Remove from "ML Models" category

- quickstarts/ollama/config.yml
This points the Ollama quickstart to the new AI Monitoring installation approach (directly through the APM agent). The default dashboard does not really make sense for an app that uses Ollama so I'm removing the link to that. The curated AI Monitoring pages (or the new entity's page) is probably where we should send the user but it doesn't seem like we can easily hook that up via the quickstart config
> Point Ollama to the updated AI Monitoring installer

- dashboards/lambdatest/lambdatest-logs.json
Adding a new page containing widgets related to HyperExecute testing platform of LambdaTest.
> LambdaTest: added new page for HyperExecute widgets

- quickstarts/azure-openai/config.yml
Azure OpenAI should only show up under Generative AI/LLMs, not the ML Models category.
> Remove Azure OpenAI from mlops category

- .github/pull_request_template.md
- CONTRIBUTING.md
https://new-relic.atlassian.net/browse/NR-294934
Adding docs indicating standalone Alerts are deprecated.
> docs: Add alerts deprecation to docs

- quickstarts/battlesnake/config.yml
Removing some tagging from the battlesnake quickstart.
> Remove battlesnake from core listings

- data-sources/vertx-extensions/config.yml
https://new-relic.atlassian.net/browse/NR-307149
Duplicate vert.x tiles show, removing the vert.x data source and leaving the quickstart.
> feat: Remove vert.x data source from add data

- dashboards/gcp-redis/gcp-redis.json
Corrected NRQL used for Replication byte offset widget. 
Changed from average(replication.master.slaves.Offset) to average('replication.master.slaves.Offset')
- [N/A] Does the PR contain a screenshot for each of …
> Updated replication.master.slaves.Offset NRQL

- dashboards/slow-nrql-queries/slow-nrql-queries.json
- updates the scanned events chart to use an estimate based on NrComputeUsage (makes it supported by all accounts)
- removed two unnecessary charts form the scanned events panel.
> Cleaned Up Scanned Events Panel

- quickstarts/haproxy/config.yml
Updated the documentation URL for Haproxy quickstart, which was showing previously 404 page not found error
Haproxy docs link: https://docs.newrelic.com/install/haproxy/
> Updated doc URL for Haproxy quickstart

- quickstarts/sendgrid/config.yml
As we prepare to remove the Amazon S3 tile from the UI, including deleting the associated datasource, we aim to eliminate SendGrid's dependency on Amazon S3. We have replaced it with our new AWS integration, allowing customers to send their logs from S3 using this updated integration.
> Replaced Amazon S3 with amazon-web-services in sendgrid integration

- quickstarts/sendgrid/config.yml
As we prepare to remove the Amazon S3 tile from the UI, including deleting the associated datasource, we aim to eliminate SendGrid's dependency on Amazon S3. We have replaced it with our new AWS integration, allowing customers to send their logs from S3 using this updated integration. This PR includes change in the description of the quickstart.
> Update Sendgrid Description

- quickstarts/postgresql/config.yml
Updated the documentation link of postgres as this https://docs.newrelic.com/install/postgresql/ instead of https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration/
> Updated documentation link for postgres

- alert-policies/browser/AjaxResponseCodes.yml
- alert-policies/browser/AjaxThroughput.yml
- alert-policies/browser/AjaxTimetoSettle.yml
- alert-policies/browser/FirstInputDelay.yml
- alert-policies/browser/JSErrors.yml
- alert-policies/browser/LargestContentfulPaint.yml
- alert-policies/browser/PageloadTime.yml
- alert-policies/browser/Throughput.yml
Importing the Browser Alert Conditions results in a Validation Error:
This is due to the following error:
The PR fixes that by setting the Term duration to 600 seconds (10 minutes), keeping the sliding window duration at 30 seconds.
> Set term duration to a multiple (600) of sliding window (30)

- dashboards/confluent-cloud/confluent-cloud.json
This task involves adding connector and KSQL metrics tabs to the Confluent Cloud dashboard. Please refer to the documentation for connector and KSQL metrics: https://api.telemetry.confluent.cloud/docs/descriptors/datasets/cloud.
> feat: NR-411668 connector and ksql dashboards

- dashboards/java/java.json
This PR fixes the fact that the Java quickstart dashboard would always be added to an account with broken widgets because all the timeslice metrics queries require a `WHERE appName\entity.guid` in order work. Since you can't hardcode these into a quickstart dashboard, I have made some improvements using dashboard variables. (you can also add `WHERE appName LIKE '%'` but this method allows users to filter apps with the dashboard variable. 
- Add javaAppNames dashboard variable for application-specific filtering
- Update all NRQL queries to use the new filtering mechanism
- Improve query structure with proper WHERE clauses and FACET statements
- Add widget IDs, page GUIDs, and enhanced chart configurations
- Ensure all dashboard widgets filter data by selected Java applications
> feat: enhance Java dashboard with app filtering and improved queries
